Documentation/README.md, Documentation/bootkube.md, contrib/bootkube/README.md, contrib/bootkube/kube-router-cfg.yaml, contrib/bootkube/kube-router.yaml
Manifests and instructions for Bootkube + Kube-router.
Fixes: #11
=> Bootkube Integration

app/controllers/network_policy_controller.go
=> Handle invalid NetworkPolicy definition

.travis.yml, Makefile, build/travis-deploy.sh, build/verify-gofmt.sh
* One image per PR
* Don't use Travis deploys
* Fix if statement in YAML
=> CI: Small travis/makefile fixes

Documentation/README.md, README.md
@murali-reddy  I'd like your opinion on how I worded the first sections of the README.  It's a little more enthusiastic and aggressive in pointing out differences to other projects.  Otherwise I think it's easier to read.  I'm sure there's some internal links I broke, I'll check that stuff out next.
[skip ci]
=> Docs: Reworded, reorganized features

.gitignore, Dockerfile, Documentation/pod-toolbox.md, Makefile, build/image-assets/bashrc, build/image-assets/motd-kube-router.sh, build/image-assets/profile, build/image-assets/vimrc
Fixes #36 
See the new documentation for details.
=> Add Pod Toolbox features to the container

daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml
These changes will help kube-router default daemonsets run more seamlessly with kubeadm and other environments that use taints/tolerations.
=> Daemonset updates

kube-router.go
Fixes #59
https://github.com/kubernetes/kubernetes/issues/17162
=> Apply glog/goflag noisy log workaround

kube-router.go
The last commit broke logging to stderr.  I'm going to let the image build and see if this fixes it.
=> Fix logging to stderr

app/controllers/network_routes_controller.go
=> add a BGP export policy on each node so that, learned routes from iBGP peers are never advertised to global peer

app/controllers/network_policy_controller.go, app/watchers/network_policy_watcher.go
with this refactoring support for network policy V1 (or GA) is added.
Changes are backward compatible so beta network policy semantics
are still available for k8s ver 1.6.* and less
Fixes #16
=> support for network policy GA

app/controllers/network_policy_controller.go
Fix ensures below two cases are explicitly handled
- in the network policy spec for the ingress rule, its optionsl to give 'ports' and 'from' details
when not specified it translates to match all ports, match all sources respectivley
- user may explicitly give the 'ports' and 'from' details in the ingress rule. But at any given point
its possible there is no matching pods (with labels defined in 'from') in the namespace.
Before the fix both the cases were handled similarly resulting in unexpected behaviour
Fixes #85
=> GA network policy does not reject if there is not a single source pod matching a policy

app/controllers/network_policy_controller.go
as per semantics https://kubernetes.io/docs/api-reference/v1.7/#networkpolicy-v1-networking
Fixes #90
=> Netork policy GA: select all pods in namespace if pod selector is not specified in the network policy spec

app/controllers/network_routes_controller.go, app/watchers/network_policy_watcher.go
=> network_route_controller: Avoid redundant policy sets

app/controllers/network_routes_controller.go
- create a ipip tunnel interface from each node to nodes in the different subnet
- insert route to local routing table using tunnel device
Fixes #92
=> Use IP-IP tunnelling for cross-subnet pod connectivity

app/watchers/network_policy_watcher.go
=> segmentation violation when kube-router is not able to contact api server

Documentation/bootkube.md, Documentation/developing.md, Documentation/testing.md, Makefile, app/watchers/network_policy_watcher.go, hack/sync-image-cache.sh, hack/vagrant-common.sh, hack/vagrant-image-update.sh, hack/vagrant-up.sh
- `make vagrant-image-update` target added
- Documentation added and small reorganization
- Small doc fixes
=> Support updating kube-router in a running local VM cluster

Documentation/kubeadm.md, daemonset/kubeadm-kuberouter.yaml
=> kubeadm RBAC fixes and cluster setup with kubeadm instructions

Documentation/README.md, Documentation/kubeadm.md, daemonset/kubeadm-kuberouter-all-features.yaml
=> use kube-router as kube-proxy replacement

glide.lock, glide.yaml, vendor/github.com/osrg/gobgp/README.md, vendor/github.com/osrg/gobgp/config/default.go, vendor/github.com/osrg/gobgp/gobgpd/main.go, vendor/github.com/osrg/gobgp/server/sockopt_linux.go, vendor/github.com/osrg/gobgp/server/sockopt_linux_test.go, vendor/github.com/osrg/gobgp/table/message.go, vendor/github.com/osrg/gobgp/table/message_test.go
Fixes #123 
Applies upstream GoBGP fix for leaking socket fds.
https://github.com/osrg/gobgp/commit/f615fa49a768bb358e6318e64dc42e9a6af10681
=> vendor: Update GoBGP to fix fd leak

app/controllers/network_routes_controller.go
=> Add iptable rule in filter table FORWRD chain to allow traffic in and out to the pods

app/controllers/network_policy_controller.go, app/watchers/namespace_watcher.go
Handle namespaceSelector in NetworkPolicyPeer
Fixes #112
=> NetworkPolicy: Fix e2e test failures

app/server.go
Removes the multiple stop channels. The same effect can be reached by a single stop channel that is closed. 
This removes complexity.
=> Consolidate multiple stop channels into one

app/controllers/network_routes_controller.go
https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/#network-plugin-requirements
Fixes #141
=> Enable netfilter for bridge, a must requirement for all CNI that use bridge

app/controllers/network_policy_controller.go, app/controllers/network_routes_controller.go, app/controllers/network_services_controller.go
=> fix gofmt, go_vet, misspells

app/controllers/network_policy_controller.go
=> Fix conditional so only matched pods are firewalled

app/controllers/network_policy_controller.go
=> Network policy egress support

app/controllers/network_policy_controller.go
Support for IPBlock specified in the ingress rule/egress rule of network policy spec
Fixes #144
=> Support CIDR in network policy ingress and egress rules

app/controllers/network_policy_controller.go
Network policy: always permit traffic from local node to the pods irrespective of network policies
fixes #87
=> Network policy: always permit traffic from local node to the pods

app/controllers/network_routes_controller.go
=> Fix to avoid re-adding existing BGP export policy, and policy assignment

app/controllers/network_services_controller.go
=> Support for Services with externalIPs

app/controllers/network_services_controller.go
- as you annotate and remove DSR annotation, switch the IPVS server
type to tunneling to masqurade mode
- also restrict preparing the pod for DSR only to the local pods
=> Direct Server Return Fixes

app/controllers/network_services_controller.go
- add a route to exteranl ip in custom routing table to prevent martian packets
- switch between Masqurade and Tunnel for forwarding when DSR in disabled and enabled
=> Fixes direct server return on exteranl IP's

app/controllers/network_services_controller.go
Fixes #139 so that the `--nodeport-bindon-all-ip` option so that it creates an IPVS service for each interface IP. I have tested this on my own systems and it is working wonders.
Right now I only have it deliberately create IPVS servers for IPv4 addresses, but it is possible this solution could work for IPv6, I just have not tested.
Certain interfaces are ignored by simply reading the name. For example a "kube" interface's IPs are ignored since a service is not necessary.
I am by no means seasoned in Go so feel free to complain about wierdness or inconsistancies :)
=> Fix --nodeport-bindon-all-ip

app/controllers/network_routes_controller.go
Earlier when pod is launched on the node bridge CNI plug-in was setting up. Which leads to errors when no pod is launched on a node.
Fixes #223
=> explicilty create `kube-bridge` interface.

app/controllers/network_routes_controller.go
This flag was recently added in https://github.com/cloudnativelabs/kube-router/pull/220, but the check to enable it for global peers was missed. 
cc @murali-reddy
=> --bgp-graceful-restart should apply for global peers

app/controllers/network_services_controller.go
The option was not plumbed through to the controller.
=> Fix --hairpin-mode=true

app/controllers/network_services_controller.go
Fixes #248 
Details:
https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix
https://github.com/docker/libnetwork/issues/1113
https://groups.google.com/forum/#!topic/golang-dev/6G4rq0DCKfo/discussion
For now add all safety checks, but if we still see the issue, need to do hacks suggested.
=> Fix potential issues in DSR due to Golang limitations in switching network namespaces and add verbose logging

app/controllers/network_policy_controller.go
Use utils/ipset.go Set.Refresh instead which internally uses ipset swap
Fixes #228
=> Prevent slice representing ipset growing forver resulting in excessive memory usage

app/controllers/network_routes_controller.go, app/controllers/network_routes_controller_test.go
Also refactors `activeNodes` to not use a global variable, this makes testing easier as we don't have to clear the map between test cases.
=> Unit Tests for Node Update Events

app/controllers/network_routes_controller_test.go
cc @murali-reddy 
https://github.com/cloudnativelabs/kube-router/issues/229
=> unit tests for syncInternalPeers()

CONTRIBUTING.md
=> Fix typo in document

Documentation/README.md, app/controllers/network_services_controller.go, app/options/options.go
- Updated readme
- Added option to change prometheus port
- Added option to change prometheus path
=> Added cli config for changing prometheus port & path

Documentation/README.md, Documentation/generic.md, Documentation/metrics.md
- Added metrics section in main readme
- Added some missing requirements in the generic kube-router docs
- created metrics.md with the basic info needed to get autoscraping & sd going with Prometheus
=> Documentation updates

app/controllers/network_services_controller.go
support service.spec externalTrafficPolicy=Local. Takes precedence over `kube-router.io/service.local` annotation.
Also dynamically cleanup service endpoints based on the service spec is set for Local only services or not.
=> support service.spec externalTrafficPolicy=Local

Makefile, app/options/options.go, app/server.go, kube-router.go
Also print the version info at startup.
=> Adding --version / -V support to print version information

Documentation/pod-toolbox.md
=> fix Pod Toolbox documentation issue

Documentation/bgp.md, app/controllers/network_routes_controller.go
Enable Route Reflector feature as discusses in issue #192 . 3rd try.
=> Feature Route Reflector

app/controllers/network_routes_controller.go, app/controllers/network_routes_controller_test.go, app/watchers/endpoints_watcher.go
cc @murali-reddy @roffe 
Something to consider for the future. IETF RFC4786 outlines:
```
Frequent advertisements and withdrawals of individual prefixes in BGP
are known as flaps. Rapid flapping can lead to CPU exhaustion on
routers quite remote from the source of the instability, and for this
reason rapid route oscillations are frequently "dampened", as
described in [RFC2439].
```
Crashing pods or rolling updates of large deployments can cause excessive route flapping, I think the impact it will largely depend on the setup of global peers and the size of the cluster. My guess is that very few people will run into issues with route flapping.
=> Route advertisement should account for services using externalTrafficPolicy=Local

app/controllers/network_services_controller.go
=> close docker client after use

app/controllers/network_routes_controller.go
OnNodeUpdate dont perform disableSrcDstCheck until first round disableSrcDstCheck() is performed at start
=> limit disableSrcDstCheck performed on OnNodeUpdate()

app/controllers/network_routes_controller.go, app/controllers/network_routes_controller_test.go
* also fixes bug where default policy was temporarily set to `ACCEPT`   
cc @murali-reddy @roffe
=> Test_addExportPolicies

CHANGELOG.md
=> Add CHANGELOG starting with v0.2.0-beta.1

pkg/controllers/network_policy_controller.go, pkg/controllers/network_routes_controller.go, pkg/controllers/network_services_controller.go
when full-sync is in progress at controller's boot time, processing updates are not necessary, so skip them. Event in to corner case if full-sync does not cover an update to a resource, next periodic full sync will reconcile the change.
=> prevent processing updates leading to sync when controller doing full-sync at boot time

pkg/cmd/kube-router.go, pkg/controllers/network_policy_controller.go, pkg/controllers/network_routes_controller.go, pkg/controllers/network_services_controller.go, pkg/healthcheck/health_controller.go, pkg/metrics/metrics_controller.go
no functional change, just moving the health and metrics to sepearate packages
=> move health, metrics to sepearate packages

pkg/controllers/proxy/network_services_controller.go
=> proxy: cleanup stale IPs on kube-dummy-if

docs/kubeadm.md
- Repository URL changed
- Update version
- Update flag (see #278)
=> Update kubeadm iptables cleanup command

pkg/controllers/proxy/network_services_controller.go
Implementing a TODO to cleanup external IP routing table entries.
=> cleanup routing table 79 (external IPs)

pkg/controllers/proxy/network_services_controller.go
=> use node ip as source when accessing service VIP's from the node

pkg/controllers/proxy/network_services_controller.go
Closes https://github.com/cloudnativelabs/kube-router/issues/413
=> Fix LVS failover not working with UDP packets

docs/user-guide.md, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/routing/network_routes_controller.go
=> Fix NPE when performing cleanup()

pkg/controllers/netpol/network_policy_controller.go
* Instead of clearing the iptables firewall chains for each resync, new chains are now generated side-by-side with the existing ones.
* Chain naming now has an addition component, version, which ensures chain name uniqueness.
* Existing cleanup procedure for stale iptables rules will handle garbage collection of unused chains.
=> Fix for network policy connection refused issue (#461)

pkg/controllers/netpol/network_policy_controller.go
Ref: #461 #477 
* use strconv for converting int64 to string
* change order of pod-fw sync, chain items has to be added before jumping to the chain starts
* added logging of syncversion, decreased logging verbosity+severity for planned chain cleanups
=> Fix nwplcy re-sync issue (#477)

pkg/controllers/netpol/network_policy_controller.go
fix #481 
Preprocess k8s version's Minor to drop suffix "+" before type conversion
=> processing k8s version for NPC

docs/user-guide.md, pkg/cmd/kube-router.go, pkg/healthcheck/health_controller.go, pkg/options/options.go
fix #489
Improve health check for cache synchronization. See the issue above for more details.
=> Improve health check for cache synchronization

pkg/controllers/proxy/network_services_controller.go
=> [jjo] ipAddrDel(): also delete VIP local rt addition

pkg/controllers/netpol/network_policy_controller.go
Make the comments of the iptables rules in NWPLCY chains more accurate and reasonable.
=> Make the comments of the iptables rules in NWPLCY chains more accurate and reasonable

docs/ipv6.md
Add a document to track ipv6 support.
=> Added ipv6 documentation

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
=> add toleration for nodes with taint node.kubernetes.io/not-ready

pkg/controllers/netpol/network_policy_controller.go
network policies with named ports is still not supported in kube-router. This pr ensures if a network policy is configured with a named port just skip processing the policy.
ref https://github.com/cloudnativelabs/kube-router/issues/338
@jimmy-zh please review
=> handle network policies with named ports gracefully

pkg/controllers/routing/network_routes_controller.go
=> Minor typo fix in logs

pkg/controllers/netpol/network_policy_controller.go
Fixes #338 #375 
Support `named port` of network policy.
=> Support named port of network policy

Makefile, vendor/github.com/osrg/gobgp/server/sockopt_linux.go
=> Use x/sys/unix epoll

docs/kubeadm.md
A suggested fix for https://github.com/cloudnativelabs/kube-router/issues/760
=> Updated the kube-proxy cleanup command to use the newer version

contrib/bootkube/kube-router.yaml, daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml, docs/generic.md, docs/kubeadm.md, docs/user-guide.md
=> Add PriorityClass and docs update

USERS.md
=> adding kube-router users list

USERS.md
=> add enix as user

USERS.md
Thanks again for your hard work
=> Add Numberly to USERS.md

pkg/controllers/routing/network_routes_controller_test.go
Fix unit test failure due to switch of listing node API objects from API server to cached informer. Modify test to use informer
=> fix Test_syncInternalPeers test failure due to #864

pkg/controllers/netpol/network_policy_controller.go
There is a iptables rule in `filter` table `FORWARD` chain to ensure pod egress traffic is run through the network policies however this rule only takes care of pod accessing destination pod directly by its IP.
When a pod access a service which eventually gets DNAT'ed we need to add a rule in `OUTPUT` chain as well to enforce network policies. 
Fixes #609
=> run network polices on pod egress traffic going through the OUTPUT chain of filter table

pkg/controllers/routing/ecmp_vip.go
=> withdraw external IP from advertisement only if the deleted service is the last service using external IP

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
=> mount host /run/xtables.lock to kube-router container 

.travis.yml
https://github.com/estesp/manifest-tool/releases/tag/v1.0.2
=> .travis.yml: Update manifest-tool to 1.0.2

.goreleaser.yml, Makefile
Support other arches as well, so they will appear as tarballs on releases
=> .goreleaser.yml: Multiarch build

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
Seems kinda pointless to depend on two images when one is enough :-)
=> Use same image for container and initContainer

pkg/controllers/netpol/network_policy_controller.go
This is a fix for #896 where we started adding egress references to the INPUT table, but didn't add something to cleanup references in the INPUT table before trying to remove our custom pod FW chains.
This code now ensures that we check all of the primary iptables chains of the filter table for references before we remove those references and ensures that we don't end up in a situation where we continually add to our iptables chain references.
I was able to reproduce the bug in a small development cluster and saw that the number of iptables objects increased by about 110 references every 15 seconds. With this patch applied I see the object count staying the same over the course of 30 minutes.
=> Fix Network Policy Cleanup Code

pkg/controllers/routing/bgp_policies.go
=> fix false negative errors in creating BGP defined sets

pkg/controllers/netpol/network_policy_controller.go
addressing review comment https://github.com/cloudnativelabs/kube-router/pull/914#discussion_r439702084
=> avoide listing a chain if the rule already exists

pkg/controllers/proxy/network_services_controller.go
=> proxy: only output Error log when there's an error

docs/user-guide.md, pkg/cmd/kube-router.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
Same as #799 with some minor fixups so that it will build since it had been a long time since the author had submitted and wasn't responding on the PR.
FYI @murali-reddy
=> Allow Setting BGP Restart Time

.golangci.yml, pkg/cmd/kube-router.go, pkg/controllers/netpol/namespace.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/routing/aws.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go, pkg/controllers/routing/utils.go, pkg/options/options.go, pkg/utils/ipset.go, pkg/utils/pod_cidr.go
https://travis-ci.org/github/cloudnativelabs/kube-router/jobs/702116610#L275-L331
=> [testing] run go linters

pkg/controllers/netpol/network_policy_controller.go
Not sure how I missed these minor gofmt problems with my PR on #970, but this fixes that.
=> fix(network_policy): missed gofmt on #970

pkg/controllers/routing/network_routes_controller.go
@murali-reddy this should resolve the NextHop issue that I pointed out in slack where neighbor IP can be either the node itself in a full mesh scenario or a different BGP speaker acting as a route-reflector. This code ensures that the route added contains the nextHop similar to the logic that we had when using GoBGP 1.X
Tested it against our cluster and all of the routes went back to normal.
=> fix(nrc): update to use nextHop attribute from path

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go
https://travis-ci.org/github/cloudnativelabs/kube-router/builds/721516238#L273-L278
=> fix build break due to go linter errros

.travis.yml, Dockerfile, Makefile
Updating golang to 1.15 and the base image to alpine 3.12
Testing if CI will still pass.
=> Update to golang 1.15 and alpine-3.12

pkg/controllers/routing/ecmp_vip.go
@murali-reddy I'm still in the process of testing this, but wanted to get it in early for you to begin looking over.
Basically, when there are service/endpoint changes, this forces the NRC to consider all services and not just the single service that was updated. In this way it's able to properly evaluate changes to routing when multiple services may share the same externalIP.
This is similar to what `AddPolicies()` (https://github.com/cloudnativelabs/kube-router/blob/53a0568ae906e94010295cb9b741837b9dacc5be/pkg/controllers/routing/ecmp_vip.go#L126) is already doing, only now we do it when considering what VIPs to advertise and which ones to withdraw.
Fixes #1012
=> fix(nrc): multiple services with the same VIP

pkg/controllers/netpol/pod.go
This PR builds on top of the changes done in #1007 
No logical changes, just modularizing to lengthy functions that are hard to understand and maintain to modular code
please see the resulting code structure first in 
https://github.com/cloudnativelabs/kube-router/blob/npc-code-restructure-1/pkg/controllers/netpol/pod.go
=> modularize the code settting up pod firewall chains

Makefile
since the project moved to go modules, glide is not used anymore.
=> Makefile: Drop outdated glide command

pkg/controllers/netpol/pod.go
fixes #1035
Now that we're not proceeding with the partial syncs that were in #1010 we should still bring this fix into the next release.
=> fix(npc): sync npc on pod label changes

cmd/kube-router/kube-router.go, go.mod, go.sum, pkg/cmd/kube-router.go, pkg/controllers/netpol/namespace.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/pod.go, pkg/controllers/netpol/policy.go, pkg/controllers/proxy/network_service_graceful.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/routing/aws.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/pod_egress.go, pkg/cri/remote_runtime.go, pkg/healthcheck/health_controller.go, pkg/metrics/metrics_controller.go, pkg/version/version.go
glog is effectively unmaintained and the kubernetes ecosystem is mainly using its fork klog.
Fixes: #1051
=> Replace github.com/golang/glog with k8s.io/klog/v2

docs/user-guide.md
Adds additional documentation to clarify #967
=> doc(user-guide.md): clarify externalips hairpin option

pkg/cmd/kube-router.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/controllers/netpol/policy.go, pkg/controllers/proxy/network_service_graceful.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/routing/aws.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/pbr.go, pkg/controllers/routing/pod_egress.go, pkg/controllers/routing/utils.go, pkg/healthcheck/health_controller.go, pkg/metrics/metrics_controller.go, pkg/options/options.go, pkg/utils/ipset.go, pkg/utils/node.go, pkg/utils/node_test.go, pkg/utils/pod_cidr.go, pkg/utils/utils.go, pkg/version/version.go
@mrueg @murali-reddy 
This fixes a bunch of linter errors that IntelliJ has brought up in the project for a while now.
Its a lot, but most of the changes follow several major themes that I have broken up by commit, so viewing by commit is probably easier.
=> Fix a bunch of lint errors

docs/user-guide.md
k0s project uses kube-router as default solution for the CNI, so I'd like to mention it in a list of the ways to check kube-router in action.
Signed-off-by: Mikhail Sakhnov <mikhail@skhnv.me>
=> Mention k0sproject in getting started guide

pkg/cmd/kube-router.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
=> fix typo Gracefule -> Graceful

.github/workflows/release.yml
This is a draft pr for moving the release steps from Travis.
=> .github: Add Go Releaser Step

.github/workflows/ci.yml, README.md
=> fix(README.md): update badge link to GitHub Actions

pkg/controllers/routing/bgp_policies_test.go
=> Missing bgp policies tests

pkg/controllers/netpol/network_policy_controller.go
@murali-reddy 
Fixes #1155 
Don't use the exit code of NewChain() to decide if the chain exists or not as it doesn't appear to be consistent between nftables and legacy iptables implementations.
Note this increases the number of execs that are run during NPC syncs, which is unfortunate. Hopefully these last executions will go away when we consolidate our iptables logic.
=> fix(NPC): don't rely on exit code for chain check

pkg/controllers/routing/network_routes_controller.go
=> fix(bgp): use PeerState_ESTABLISHED logic like function name(#1184)

pkg/controllers/netpol/pod.go
English is not my native language, but "traffic traffic" looks like a typo :)
=> Fix typo in filter rule comment

pkg/controllers/proxy/network_services_controller.go
Fixes #1196 (Addendum)
We should only add hairpinning rules for pods that are local to the endpoint.
Given that the definition of hairpinning is when a pod talks to itself via its service endpoint, these flows must be local in order to be valid. However, the way we implement hairpinning right now is that we add all pods and all endpoints to the `KUBE-ROUTER-HAIRPIN` chain, even ones that don't have a local endpoint.
This creates a needless number of execs since these are still handled via single iptables rules. It also creates additional time that the kernel processes rules in the data path.
When I deployed this change to our test cluster with ~300 pods running on it to a node with relatively few pods running on it, the number of hairpin rules went from ~350 to ~5. …
=> feat(nsc): only hairpin endpoints on local node

go.mod, go.sum
=> go.mod: Update containerd to 1.5.9

.github/workflows/ci.yml
Added multiarch image build support for s390x. 
Tested multiarch image build support for s390x on private repo with GHA on push and PR events.
=> Added multiarch image build support for s390x

docs/generic.md, docs/kubeadm.md
@mrueg 
Updates documentation to use a newer version of kube-proxy and also add the commands to use containerd for cleanup.
=> doc: update kube-proxy cleanup commands

pkg/controllers/routing/network_routes_controller.go
When tunnel interface's source address is on loopback, the tunnel should not be bound  to `lo`. Otherwise, packets cannot leave from egress interface to the tunnel peer.
=> skip binding device to ipip tunnel if node's interface is loopback

pkg/controllers/netpol/network_policy_controller.go, pkg/utils/iptables.go
=> fix(NPC): make code more understandable

.github/workflows/codeql-analysis.yml
=> .github/workflows/codeql-analysis.yml: Update to v2

pkg/utils/ipset.go, pkg/utils/ipset_test.go
@mrueg @murali-reddy 
On Linux kernels >5.10 there is was a new option added to ipset where a hexadecimal value was persisted from the kernel to the userspace so that ipsets could be restored exactly as they were by referencing the same randomized set string.
However, kube-router is not able to benefit from that as it often changes the ipset between "ipset save" and "ipset restore" actions. Additionally, it utilizes the options that it gets from the save verbatim in both a temp set and the final set that it swaps into to prevent data path disruptions.
Finally, it bases the number of temporary sets it has to create based on unique sets of options. Since initval is intentionally unique between each set, it causes us to execute many more options than we actually need to and reduces …
=> fix(ipset): remove initval during ipset parse

pkg/controllers/routing/network_routes_controller.go
This PR prevents troubles in the following rare scenario.
When upgrading from pre v1.1.0 version, install-cni container in a pod writes NodeIP's link MTU (e.g. 65536) to the CNI config file even when it's larger than kube-bridge's max MTU (e.g. 65535).
Then the main container tries but fails to set kube-bridge's MTU to 65536, leaving kube-bridge's MTU unchanged (e.g. 1500).
But because the CNI config file (/etc/cni/net.d/10-kuberouter.conflist) keeps its MTU as 65536, and because the node's CRI uses this value, it fails to create a veth pair and consequently can no longer create a container.
This patch, in the above scenario, rewrites kube-bridge's MTU as 1500 in the CNI config file.
=> fix invalid MTU in CNI config file

Makefile
@mrueg 
`RUNTIME_BASE` and `BUILDTIME_BASE` are both consumed in the Dockerfile and handle setting the base containers used for both building and running kube-router. These are handled differently in CI using GitHub actions than they are for local builds.
This updates the Makefile so that local builds behave the same way that CI based builds in GitHub are when it comes to these bases.
=> feat(Makefile): make local builds behave like CI

.github/dependabot.yml
Add a config to bump github-actions regularly as well.
=> .github: Add github-actions dependabot config

docs/ipv6.md
Document differences in `--override-nexthop` in v2.x versions of kube-router
=> doc(ipv6): add differences in --override-nexthop

Makefile
Bump the versions in the makefile as well @aauren
=> Makefile: Bump go + alpine as well

Makefile
@mrueg 
Various fixes for linting and moqing that have been driving me a bit nuts lately. See commit comments for more information on each change.
=> Update Linting and Moq'ing

Makefile
@mrueg 
Update version and build date setting for v2
Fixes: #1555
=> fix(Makefile): version and build date for v2

docs/user-guide.md
Fix a broken link and edit for active voice.
Document how to configure a service to use the maglev scheduler.
=> docs: improve scheduler docs

.github/workflows/ci.yml, .goreleaser.yml
@mrueg - Updates goreleaser to v6 along with the new version of the file
Followed the instructions here: https://goreleaser.com/blog/goreleaser-v2/#other-news
=> feat(goreleaser): update goreleaser-action v5->v6

.goreleaser.yml
=> .goreleaser.yml: Fix ldflag paths

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/pod.go
@QlemWasTaken
This commit allows ICMP traffic always, not just on the case that network policy is not applied in a particular direction, as was originally the intention for KUBE-NWPLCY-DEFAULT. Most crucially, this fixes IPv6 use-cases where an egress policy was applied to a workload, where ICMP traffic is used for neighbor discovery and solicitation.
This commit also consolidates common matching logic for established / related & invalid traffic flows which hopefully reduces how much iptables rules we have to make by a significant factor.
This should fix #1895 
Tagged for review: @jnummelin @rbrtbnfgl @mrueg @twz123 @catherinetcai
=> Fix IPv6 NDP on Egress Policy Use Cases
