Documentation/bootkube.md
The URL for downloading the manifests was incorrect, oops.  This fixes that.
=> Docs: fix curl commands in bootkube.md

app/controllers/network_policy_controller.go, app/controllers/network_routes_controller.go, app/controllers/network_services_controller.go, app/options/options.go, app/server.go, kube-router.go
Add some extra context to errors for debugging as well.  Tested on my local cluster with quay.io/bzub/kube-router:graceful-cli
=> Remove panics, add --help/-h flag for usage

Documentation/README.md, app/controllers/network_services_controller.go, app/options/options.go
Tested on my local cluster with quay.io/bzub/kube-router:hairpin-mode
Fixes #9
Test examples:
```
kubectl -n default run alpine --command --image alpine --replicas 2 --port 80 --expose sleep 300d
```
IPs:
```console
$kubectl -n default get pods,services,endpoints -o wide
NAME                         READY     STATUS    RESTARTS   AGE       IP         NODE
po/alpine-4025682865-7r4tw   1/1       Running   0          1h        10.2.0.2   node3-test.zbrbdl
po/alpine-4025682865-pqdfr   1/1       Running   0          1h        10.2.1.8   node2-test.zbrbdl
NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE       SELECTOR
svc/alpine       10.3.0.64    <none>        80/TCP    1h        run=alpine
svc/kubernetes   10.3.0.1     <none>        443/TCP   1h        <none>
NAME …
```
=> NetworkServiceController: Add hairpin-mode support

.gitignore, .goreleaser.yml, .travis.yml, CONTRIBUTING.md, Documentation/README.md, Documentation/developing.md, Makefile, app/controllers/network_policy_controller.go, app/controllers/network_routes_controller.go, app/watchers/node_watcher.go, build/get-git-tag.sh, build/verify-gofmt.sh, utils/node.go
WIP. Do not merge.
TODO:
See the new releasing guide in the CONTRIBUTING doc and the new Makefile for design details.
Also here's an example of a custom release pushing images to a registry: https://quay.io/repository/cloudnativelabs/kube-router?tag=latest&tab=tags
So when the official release workflow is used with Travis-CI, we should see a clean dockerhub repo of released + latest tag.
Here's an example of a kube-router-git repo for per-commit and PR images: https://quay.io/repository/cloudnativelabs/kube-router-git?tag=latest&tab=tags
=> CI: Automated build/release workflow

Makefile
Affects the dev image repo only: `cloudnativelabs/kube-router-git`
=> Don't put -latest on dev image tags

README.md, app/controllers/network_routes_controller.go, app/controllers/network_services_controller.go, app/options/options.go
Fixes  #51 
Tested with kops + AWS.
Start a simple http server deployment:
```console
kubectl -n default run alpine --command --image alpine --replicas 2 --port 80 -- httpd -fv
```
Expose as LB type service:
```console
kubectl -n default expose deployment alpine --port 8888 --target-port 80 --type=LoadBalancer
```
Check Services and EPs:
```
$ kubectl -n default get service,ep -o wide
NAME             CLUSTER-IP      EXTERNAL-IP                                                              PORT(S)          AGE       SELECTOR 
svc/alpine       100.69.95.246   aa5fdbd3a667c11e7b2ff0691ff4e598-286081594.us-west-2.elb.amazonaws.com   8888:32667/TCP   17m       run=alpine                                  
svc/kubernetes   100.64.0.1      <none> …
```
=> services-controller: Add LoadBalancer Service support

app/controllers/network_routes_controller.go
=> on BGP peer down, advertised route from peer is not cleaned-up in local routing table

app/controllers/network_routes_controller.go
=> BGP export polices to advertise routes so that extra hop is avoided

app/controllers/network_services_controller.go
=> fix null pointer dereference during kube-router --cleanup-config

app/server.go
This allows using the service account credentials generated by kubernetes for accessing the api server, and auto discover the api server. If config file location is provided, it will use it as before. 
Tested in kubeadm kubernetes 1.7.
=> Using inclusterconfig for default configuration

Makefile
gobgp client inside the kube-router container will now always be in sync with the gobgp library used to build the kube-router binary.
=> Use vendored gobgp to build gobgp client

app/controllers/network_services_controller.go
=> Randomize service endpoint addition when configuring destination on ipvs service

app/controllers/network_routes_controller.go
=> reduce ipip tunnel MTU by 20 bytes to accommodate the tunnel overhead

Makefile, hack/vagrant-common.sh, hack/vagrant-destroy.sh, hack/vagrant-up.sh
- Fixes a bug that would cause a failure to use a local build's image in the cluster.
- Fixes a bug that would cause the vagrant destroy process to be skipped.
=> vagrant: Local cluster enhancements

Documentation/README.md, app/controllers/network_routes_controller.go, app/controllers/network_services_controller.go, app/options/options.go
- ~~Removes flag "--cluster-cidr"~~
- Depreciates flag `--cluster-cidr`
- Adds flag `--enable-pod-egress` (default: true)
- Removes previously created iptables rule if option is changed to false
- Uses ipset of PodCIDRs from active nodes for iptables matching
Fixes #107 if workable.
~~@murali-reddy this uses `currentCidr` which is the Pod subnet local to the node, rather than the entire PodCIDR for all pods. Do you see any issues from this? Seems that any particular node shouldn't care about masquerading traffic for another node's Pod subnet, but I may be mistaken.~~
I'm running k8s conformance tests now, will update when complete.
=> Enable pod egress masquerading by default

build-image/Dockerfile, build-image/entrypoint.sh, build-image/make.sh
Because of netlink kube-router can't be built on MacOS.
This adds a folder with a "make.sh" script to build kube router.
Integration into Makefile outstanding.
=> Add build-image folder, which allows to build kube-router on mac os

app/controllers/network_routes_controller.go
Setup policy-based routing so that traffic arriving on a tunnel interface leaves on same tunnel interface irrespective of rp_filter value
- add ip rule to look up traffic from the pods from a custom route table
- in the custom route table, add entry to route traffic to remote node through tunnel interface
Fixes #138
=> Setup policy-based routing so that traffic arriving on a tunnel interface leaves on same tunnel interface irrespective of rp_filter value

Documentation/README.md, app/controllers/network_services_controller.go, app/options/options.go
NodePort service listens on all ip/interfaces in case of kube-proxy. Currently kube-router listens only on node IP. This fix introduces flag `nodeport-bindon-all-ip` with which you can have kube-proxy like behaviour. If not specified only nodeIP will be open for connections.
Fixes #139
=> Kube-proxy like behaviour to listen on all ip's for NodePort service.

app/controllers/network_routes_controller.go, app/options/options.go
Adding ability to disable IP-in-IP tunnelining for cross node pod-to-pod connectivity where nodes are in different subnet. With tunneling disabled its expected that
default gateway has learned the pod CIDR's allocated for all the nodes and can route
the pod-to-pod traffic across nodes in different subnets
Fixes #119
=> Adding ability to disable IP-in-IP tunnelining

app/controllers/network_services_controller.go
=> Fix IPVS persistence flag

app/controllers/network_routes_controller.go
partially addresses #155 
This will automatically detect address families that are supported to avoid errors when ipv4 or ipv6 are disabled.  A followup PR will make the address customizable via CLI flags.
=> Dynamic gobgpd listener config, fix leaked listener

Documentation/README.md, Documentation/bgp.md, app/controllers/network_routes_controller.go, app/controllers/network_services_controller.go, app/options/options.go, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml
Addresses the following item for #163
- Add flag to specify external router's MD5 password
- **BREAKING**: `--peer-router` and `--peer-asn` flags now take a slice rather than a comma separated string. In hindsight the previous type (comma separated string) may be easier to maintain consistency with annotations.
- Consolidated NRC peer fields into a []config.NeighborConfig
to store address, asn, and password for each peer.
- Use net.IP type directly in flags. pflags library will validate the input so we don't have to.
=> Add flag to specify external router's MD5 password

Documentation/upgrading.md
=> Add docs to cover upgrading kube-router

app/controllers/network_policy_controller.go, app/controllers/network_routes_controller.go, app/controllers/network_services_controller.go, utils/ipset.go, utils/node.go
=> Prevent masquerading pod -> NodeIP traffic

contrib/bootkube/kube-router.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml, hack/vagrant-up.sh
Testing these now. Should make things work better on k8s 1.8 which dropped support for the old way of defining InitContainers via annotation/JSON.
- Remove beta annotation versions of init containers
- Add YAML InitContainers spec to all manifests
- Add CNI config ConfigMap to all manifests
- Make indentation, volume names, etc consistent
- Set all kubeconfig volumes to readonly
=> Update DaemonSet manifests

app/controllers/network_routes_controller.go
Support for 32 bit ASN numbers specifically the range 4200000000 - 4294967294 as specified by RFC 6996
Fixes #194
=> Support for 32 bit ASN numbers specifically the range 4200000000 - 4294967294 as specified by RFC 6996

Documentation/README.md, app/controllers/network_routes_controller.go, app/options/options.go
Support for advertising service external IP to be configured BGP peers
introduces new flag `--advertise-external-ip`
Fixes #161
=> Support for advertising service external IP to be configured BGP peers

Documentation/README.md, app/controllers/network_services_controller.go
New annotation "kube-router.io/service.scheduler" added for selection.
Fixes #6
=> Use service annotations to choose IPVS scheduling method

Makefile, app/controllers/network_routes_controller.go, app/options/options.go, build-image/make.sh
As per: https://github.com/cloudnativelabs/kube-router/issues/219. Adds support for BGP graceful restart
```
--bgp-graceful-restart
```
Will enable BGP graceful restarts as per https://tools.ietf.org/pdf/rfc4724.pdf, which _should_ preserve routes and forwarding state of the node. The restart time will default to the hold time, happy to add a flag to set the restart time if we think that's necessary. 
Also does some cleanup in scripts and makefile, happy to move these changes in another PR :). 
cc @murali-reddy
=> Support BGP Graceful Restart

app/controllers/network_routes_controller.go, app/options/options.go
Adds a flag to enable/disable iBGP peering. Useful when you only want nodes peering with a global peer. 
cc @murali-reddy
=> add --enable-ibgp flag

app/controllers/network_routes_controller.go, app/options/options.go
Hello labs !
We ran today in a need for **eBGP** **multihop** support for external peers. 
_May it benefits everyone (and permits us to keep on-par with master 🤞 )_
Introducing the ```--peer-router-multihop-ttl``` flag. (obviously not relevant if ```ttl=1```).
```--peer-router-multihop-ttl=3``` translates in equivalent **gobgp** configuration for **external peers** : 
```
[[neighbors]]
[neighbors.ebgp-multihop.config]
enabled = true
multihop-ttl = 3
```
=> Enable support for eBGP Multihop for external peers

app/controllers/network_services_controller.go
During periodic sync of IPVS services there is a check if the required service
already existing in IPVS. For the check the list of currnet IPVS services are
read from IPVS. This is causing performance hit as number of services increases.
With this fix, Kube-router reads once from ipvs and use for further during service sync
=> IPVS periodic sync performance improvement

app/controllers/network_services_controller.go
=> prometheus service metrics

Dockerfile, app/controllers/network_services_controller.go
Fixes #157
kubernetes/kubernetes#19029
kubernetes/kubernetes#22573
=> Flush conntrack entry when UDP service endpoint is deleted

Makefile, app/controllers/network_routes_controller.go, app/controllers/network_routes_controller_test.go, app/watchers/services_watcher.go, utils/pod_cidr.go
Adds unit tests for route controller. 
cc @murali-reddy 
https://github.com/cloudnativelabs/kube-router/issues/229
=> route controller unit tests

Documentation/kubeadm.md
These docs didn't read well and possibly led the user to do a `kubeadm reset`.
=> Make kubeadm install docs clearer

app/controllers/network_routes_controller.go, app/controllers/network_routes_controller_test.go
Ran into some strange behaviour as reported [here](https://github.com/cloudnativelabs/kube-router/issues/273). Turns out it was because linux interface names cannot be more than 15 characters. Removing the `-` in the interface name ensures that we will always have at most 15 characters for IPv4. However, I do have concerns around backwards compatibility and some more work may have to be done here so that the transition is smoother. @murali-reddy would love your thoughts here.
=> tunnel interface names cannot be longer than 15 characters

app/controllers/network_services_controller.go
use case: in VNF, traffic come from external client, and go through router ECMP to k8s node.  The pod needs to know the external client IP.  To meet this case:
1. change iptables rule to avoid SNAT for traffic to the pod on local node
2.  when annotation "kube-router.io/service.local" configured on service, only add local pod as VIP back-end. 
Finally, kube-router will advertise external IP for the node, which really has the local pod and can serve the external request without SNAT.
=> support node local service without SNAT

Documentation/README.md, Documentation/generic.md, daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter.yaml
Docs and examples how to run kube-router as a DaemonSet in a generic cluster
=> Documentation how to install kube-router on generic clusters

Documentation/README.md, Documentation/generic.md
Inspired by @roffe's work, I decided to clean it up a little bit and reorganize some things.
=> Small docs fixes for setting up a generic cluster

Documentation/generic.md, daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter.yaml
After discussions with @SEJeff & @murali-reddy on Slack
- enriched docs with more reference links to the different components
- removed https:// part from `all-features` daemonsets - _**Thanks @SEJeff for spotting**_
- removed static kubeconfig when not running kube-router with service proxy - _**Thanks @murali-reddy for clarification on how kube-router gets config when service proxy is disabled**_
- added notes for req when running containerised kubelet
- added notes for when running without service-proxy
Would love you input on this PR @SEJeff
=> Updated generic cluster docs & daemonset

Documentation/metrics.md, app/controllers/network_services_controller.go
*Fixed part 2 in https://github.com/cloudnativelabs/kube-router/issues/290
*Added additional metrics
*More docs for the metrics
=> Added more metrics and small bugfix + more docs

app/controllers/network_routes_controller.go, app/controllers/network_routes_controller_test.go
Fixes panic in GoBGP library resulted to due to concurrency issue when kube-router pod is starting, OnNodeUpdate can resulting in  calling gobgp addNeighbour before GoBGP server is properly started.
=> prevent calling gobgp AddNeighbour call before GoBGP server is properly started

Documentation/health.md, Documentation/healthz.md, app/controllers/health_controller.go, app/controllers/metrics_controller.go, app/controllers/network_policy_controller.go, app/controllers/network_routes_controller.go, app/controllers/network_services_controller.go, app/options/options.go, app/server.go, daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
Running this PR in my test env over day. Please review but do not merge until I have test results.
Fixes: https://github.com/cloudnativelabs/kube-router/issues/80 and https://github.com/cloudnativelabs/kube-router/issues/171
* Added roling update strategy to all daemonsets. Max 2 unavail
* Added liveness check in daemonsets to use default health port of 20244 on /healthz
* Added health controller
Description: 
Added health controller that uses syncinterval of controllers + 5 seconds. If a controller isn't reporting in with a heartbeat within the interval it kube-router will be flagged as unhealthy on the /healthz endpoint
Docs are in health.md
=> Healthchecks

Documentation/upgrading.md, daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
reverted changes to daemonsets adding rollingUpdate and documented how to do it for cluster operators
=> reverted rollingUpdate strategy

app/controllers/network_services_controller.go
Fixes https://github.com/cloudnativelabs/kube-router/issues/304
=> Nsc conntrack fix

app/controllers/network_routes_controller.go
AWS: perform disable src-dst check only if node has necessary IAM.  Also introduce delay between ec2 api calls, so that requests are not rejected due to API throttling
Fixes: #313
=> AWS: perform disable src-dst check only if node has necessary IAM. 

Makefile
Instrument Makefile to [ab]use `GOARCH` for
*  Explicitly add `GOARCH` env to `go ...` invocations, defaulting to amd64 (implicit current default)
* Dockerfile.$(GOARCH).run overriding with proper alpine ARCH specific image
* New  `multiarch-{setup,check,binverify}` targets to aim local box cross-platform run-ability via
`/usr/bin/qemu-<ARCH>-static`
Will add comments with actual run outputs.
=> [jjo] add arm cross-compile support

Documentation/README.md, app/controllers/network_routes_controller.go, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, utils/pod_cidr.go, utils/pod_cidr_test.go
This PR addes support for hostport.
- CNI conf file to be used is moved to env variable. If env var is not present falls back to previous hard coded value i.e) `/etc/cni/net.d/10-kuberouter.conf`
- support for `.conflist` is added so you can specify multiple plug-ins
- sample [daemonset](https://github.com/murali-reddy/kube-router/blob/hostport/daemonset/kubeadm-kuberouter-all-features-hostport.yaml) is added with 
-- env variable set to `/etc/cni/net.d/10-kuberouter.conflist`
-- configmap with cni conf json with portmap plugin config
-- init container changes to add `.conflist` file
Image `cloudnativelabs/kube-router-git:hostport` has the changes in this PR.
=> [WIP] support for Hostport

Dockerfile
Couple changes to improve local development, building, etc.
* use ADD instead of COPY to force cache invalidation
* rearrange to cache more expensive network downloads (apk, etc),
ADDing locally built binaries at last
=> Dockefile: use ADD instead of COPY and rearrange

app/controllers/network_routes_controller.go
Hi guys,
I noticed that when using a Service object with type: Loadbalancer and externalTrafficPolicy: Local, the routes are not withdrawn. On my external BGP peer I could still see the route which caused for dropped packets when that route was used.
This pull request withdraws routes for this externalTrafficPolicy when there are no endpoints.
=> withdraw ClusterIP bgp route for externalTrafficPolicy=Local when there are no local endpoints

utils/node.go, utils/pod_cidr.go, utils/pod_cidr_test.go
This allows you to set pod CIDR on a node by setting the annotation `kube-router.io/pod-cidr`. The pod CIDR in the annotation takes precedence over `node.Spec.PodCIDR`. Generally people should still rely on `node.Spec.PodCIDR` (set by the control plane), but this is a nice feature to have in case you need to migrate your cluster into a new IP space.
=> allow pod CIDR to be set using node annotations

app/controllers/network_routes_controller.go
- Adding 1s delay between ec2 API calls
- node performs disable src-dst check ONLY if it has necessary IAM
=> add 1s deley between ec2 API calls, and check if node has ec2 IAM

Documentation/README.md, app/controllers/network_routes_controller.go, app/controllers/network_routes_controller_test.go, app/controllers/network_services_controller.go, app/options/options.go
* add `--advertise-loadbalancer-ip` flag, which will make Service's
Ingress IP(s)set by the LoadBalancer to:
- be locally added to nodes' `kube-dummy-if` network interface
- be advertised to BGP peers
* support "kube-router.io/service.skiplbips=true" per Service
annotation to selectively skip above
* refactor several functions with dupped code to streamline logic as:
- `getIpsToAdvertise()` which calls ->
- `getClusterIPs()`
- `getExternalIPs()`
- `getLoadBalancerIPs()`
and contains nodeHasEndpoints logic, returns:
(ipsToAdvertise, ipsToUnAdvertise)
- advertiseIPs() which is essentially previous advertiseClusterIPs()
(which was previously used to advertise _any_ IP actually, ie misnamed),
with logic to un/advertise based on both passed arguments:
(ipsToAdvertise, ipsToUnAdvertise)
This is …
=> [jjo] support advertising status.loadBalancer.ingress IPs via flag

app/controllers/network_routes_controller_test.go
Calls StartServiceWatcher and StartEndpointsWatcher in Test_addExportPolicies so that fake clientset state is cleared on each run. We should consider refactoring kube-router so we're not using global lister/watchers 
ref: https://github.com/cloudnativelabs/kube-router/pull/352
=> clear state of global service/endpoint watcher in Test_addExportPolicies

app/controllers/network_routes_controller.go
Fixes a bug where the default ASN was used (64512) even though the annotation `kube-router.io/node.asn` was set.
=> fix bug where default ASN is used for iBGP peering

daemonset/kubeadm-kuberouter-all-features-dsr.yaml
I guess the example config was copied wrong. https://github.com/cloudnativelabs/kube-router/blob/master/daemonset/kubeadm-kuberouter-all-features.yaml has `kubeconfig` set to RO but I think you need RW access to talk to docker?
Alternatively both need to be RO
=> Fixed the /var/run/docker.sock permissions in the DSR example

Documentation/README.md, Makefile, kube-router.go, kube-router_test.go
This section of the doc was fairly out of date.
Updated it, as well as added a test to ensure any future changes help changes are properly documented.
=> update command line options documentation

app/controllers/network_policy_controller.go
=> Fix networkpolicies if there are unscheduled pod, log errors (#378)

Makefile
Adde option to build in Docker, also a small check so it doesn't ask for sudo password for Docker when on OSX
`make  BUILD_IN_DOCKER=true` will run the go test & kube-router build in golang:alpine, gobgp is already build in docker container.
=> Osxcompat 1

app/controllers/network_routes_controller.go
Fixes #385 
listen just on node's IP address `172.20.46.210:179`
```
root@ip-172-20-46-210:~ #netstat -lnp | grep kube-router
tcp        0      0 172.20.46.210:179       0.0.0.0:*               LISTEN      1/kube-router
tcp        0      0 :::179                  :::*                    LISTEN      1/kube-router
tcp        0      0 :::20244                :::*                    LISTEN      1/kube-router
tcp        0      0 :::50051                :::*                    LISTEN      1/kube-router
```
=> bind GoBGP just to node IP address

docs/README.md, pkg/controllers/routing/export_policies.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go, pkg/options/options.go
Nodes advertise its pod CIDR to external BGP peers only of `--advertise-pod-cidr` is set to true (defaults to true).
This is to enable a case where pod's remain non-routable from out of the cluster but service VIP's can be routable from out side the cluster.
=> Ability to enable/disable node advertising its pod CIDR to external BGP peers

pkg/controllers/netpol/network_policy_controller.go
Fixes #412 
During recent refactoring, lister was wrongly used.
thanks @xanonid for finding the issue.
=> fix the wrong lister used

pkg/controllers/routing/network_routes_controller.go
Change the routes created to send traffic over tunnel interface from 
```
100.96.0.0/24 dev tun-172205645  proto 17
100.96.1.0/24 dev tun-1722051121  proto 17
```
to 
```
100.96.0.0/24 dev tun-172205645  proto 17  src 172.20.95.219
100.96.1.0/24 dev tun-1722051121  proto 17  src 172.20.95.219
```
Fixes #427
=> explicilty specify source IP to use when send traffic over tunnels

pkg/controllers/routing/ecmp_vip.go
Fixes #426 
With out the fix athough service VIP gets added to the gobgp RIB, then wont get advertised to peers.
During periodic sync export policies are reevaluated which will result in the VIP's getting advertised.
Thanks to @phemmer for cathing this latent issue.
=> update clusteripprefixset so that BGP export policies allow advertising the service VIP

pkg/controllers/routing/ecmp_vip.go
When service is deleted, we should be called `withdrawVIPs` for the IP's associated with the service.
=> fix wrong use of advertiseVIPs where withdrawVIPs is required

pkg/controllers/proxy/network_services_controller.go
Fix prevents unnecessary performing of clean up of external ip from PBR custom table resulting in
`E0513 06:22:31.383773       1 network_services_controller.go:1698] Failed to del route for  in custom route table for external IP's due to: exit status 255`
=> perform clean-up of external ip from custom route table for external ip only if the table is not empty

pkg/controllers/routing/network_routes_controller.go
The current stings.Contains passes checks when there is are similar IPs
Ex: 
the two ips exist `10.1.73.7` &  `10.1.73.72` where in the latter the tunnel will pass the condition for the former. This issue was encountered multiple times when there are similar IPs with the last octets sharing values. This has fixed the issue in our current environment.
=> adds explicit check for existing tunnel to avoid partial matches

pkg/controllers/proxy/network_services_controller.go
This fixes issues with ipvs services that have zero endpoints from not being cleaned up.
=> services: correct check for inactive service endpoints

pkg/controllers/proxy/network_services_controller.go
`out` variable content after executing `ip route list table` was
never used.
=> proxy: Fix ineffassign error

daemonset/generic-kuberouter-only-advertise-routes.yaml, docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
Creates a flag `--enable-cni` which can be used to disable kube-router's CNI plugin functions so that other CNI plugins can run along side kube-router to leverage BGP routing, network policies or IPVS/LVS service proxy
https://github.com/cilium/cilium/issues/2463
=> Allow CNI plugin to be disabled

pkg/cmd/kube-router.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go, pkg/healthcheck/health_controller.go
Users have been reporting failing health checks (For e.g. #396) and kube-router pod restarts due to health check failured. This PR fixes below possible issues causing the problem.
- start health controller to health check only after network policy, network service and routing controller are started
- performs less aggressive periodic health check's at 5sec interval
- on start, time delay of 1 min is added before health check controller starts health checking.
- initialize NetworkPolicyControllerAlive, NetworkRoutingControllerAlive, NetworkServicesControllerAlive values
=> fix race condition issues with health checks

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/network_services_controller_moq.go, pkg/controllers/proxy/network_services_controller_test.go
Fixes regression, where adding service VIP to the tunnel interface inside the pods when DSR is used was failing
kube-dummy-if was being used inside the pods, which does not exist in the pods.
=> Fixes regression, where adding service VIP to the tunnel interface inside the pods when DSR is used was failing

dashboard/kube-router.json, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/bgp_peers.go
=> Report delay metrics as seconds, not nanos

pkg/controllers/netpol/network_policy_controller.go
Ref: #475 
* Moved code for evaluation of policy peers into separate func to avoid code duplication
* Ensured fallback to policy namespace, if namespaceSelector is not set
- Tested on kubernetes v1.11.0 with combinations of
namespaceSelector alone
podSelector alone 
namespaceSelector + podSelector
=> Implemented the use of both namespaceSelector and podSelector

docs/bgp.md, pkg/controllers/routing/export_policies.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go
Fixes https://github.com/cloudnativelabs/kube-router/issues/469
For traffic shaping purposes, you may want to prepend the AS path announced to peers.
This PR enables that on a per-node basis with annotations:
- `kube-router.io/path-prepend.as`: AS number to be prepended
- `kube-router.io/path-prepend.repeat-n`: number of times to prepend ASN
=> Add Support for BGP Prepend

pkg/controllers/proxy/network_services_controller.go
fix case where 1 min unintended delay is added when checking for tunnel interface to come up in pod
=> fix case where 1 min unintended delay is added when checking for tunnel interface to come up in pod

pkg/controllers/routing/ecmp_vip.go
There's an edge case for services using `externalTrafficPolicy: Local` where the export policies aren't updated for up to 5m (default routes sync period) because the first Service update event fails because the corresponding endpoint was not created. This is a race condition between kube-router & the apiserver.
```
E0808 18:11:30.708175       1 ecmp_vip.go:92] error getting routes for service: nginx, err: endpoint resource doesn't exist for service: "nginx"
```
^ that log message is from [here](https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/routing/ecmp_vip.go#L92) right before the call to `nrc.addExportPolicies()`. 
This PR adds a `OnEndpointsAdd` event handler to call `addExportPolicies` in addition to `OnEndpointsUpdate` when endpoint resources are created.
=> update BGP export policies on endpoints add event

docs/bgp.md, pkg/controllers/routing/network_routes_controller.go
Modifying the fix done for https://github.com/cloudnativelabs/kube-router/issues/385 in commit https://github.com/cloudnativelabs/kube-router/commit/8c746b2cbc8026717d534236358033007fd7c9b0
Adding an option `bgp-listen-all-ip` to control on which IP GoBGP server listens on. By default value is false, and GoBGP server will just listen on node IP. When set to true GoBGP server will listen on `0.0.0.0`
This flexibility is desinrable when node is  multi-homed and GoBGP server can learn routes advertised from different networks.
cc @Thoro
=> issue-385: make it optional on which ip address BGP server listens

docs/bgp.md, docs/user-guide.md, pkg/controllers/routing/export_policies.go, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
Introduces the option --override-nexthop, setting it to true will make advertised next hop in the router to the BGP peers will be automatically selected to be appropriate reachable local IP. This will be override any next-hop set for the routes in the RIB. Kube-router by default sets the next-hop to `node IP` which is not correct in case of nodes with multiple interfaces and use different interaces for different external peers.
Fixes #480
=> Introduces the option --override-nexthop, to override the next hop used in advertised routes

docs/user-guide.md, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/export_policies.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go, pkg/controllers/routing/utils.go, pkg/options/options.go
* Introduced new cmdline flag --bgp-port, which controls BGP Server listening port and remote port of in-cluster node peers
* Introduced new cmdline flag --peer-router-ports, which controls remote BGP port for external peers
* Introduced new node annotation kube-router.io/peer.ports with same effect as --peer-router-ports
Note: Although it is now possible to specify a custom remote port for external peers, still only **one** BGPServer will be started locally, listening on the port specified with the `--bgp-port` flag. 
Hence; in case you are using a custom `--bgp-port` for in-cluster peering and different `--peer-router-ports` for external peering, the external peering connection becomes one-way (passive).
=> Added support for custom BGP ports with 179 still being default (#492)

pkg/controllers/routing/network_routes_controller.go
When --override-nexthop=ture next hop that will be advertised depends on the local IP used and the peer. So it does not necessarily be `node IP`. Hence the check 
```go
if !nrc.nodeSubnet.Contains(nexthop) && !nrc.overrideNextHop {
if !nrc.enableOverlays {
```
=> prevent IPIP tunnel creation when --override-nexthop=true

pkg/controllers/netpol/network_policy_controller.go
There are some advantages of using ipset to manage multiple CIDRs in a network policy rule:
1. Fewer iptables rules and better performance.
2. Lay the foundation for supporting the semantics of `except`. I will contribute another PR later to implement this feature.
=> Use ipset to manage multiple CIDRs in a network policy rule

docs/user-guide.md, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
When the number of nodes in a cluster is high enough, the
`disableSourceDestinationCheck()` logic creates a high number
of requests to EC2, resulting in throttling and subsequent
problems, such as the inability to attach EBS volumes. This is
not necessarily mitigated by the `ec2IamAuthorized` attribute
which was added to overcome this issue, as the number of
requests can still be high enough to reach Amazon's request
limits. In addition, it is not necessary to run this multiple
times in a loop for all the nodes in a cluster, as it is
sufficient to set it once when an instance boots.
This CLI option allows an administrator to turn off this
feature for kube-router so they can use some other means of
setting the attribute.
=> Add CLI option to toggle disabling of source-dest-check in EC2

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/routing/network_routes_controller.go, pkg/utils/ipset.go
For ipv6 and dual-stack support the `IPSet` is altered. An effort is made to be compatible with existing ipv4-only code while allowing an easy switch to ipv6-only. Dual-stack is considered in the sense that instances of `IPSet` for ipv4 and ipv6 can exist in paralell.
This PR is preliminary and intended for discussions on how to introduce ipv6-only and dual-stack, but it is a serious effort and my hope is that it will be accepted eventually.
An `isIpv6` flag is added to `IPSet` and is passed on creation;
```
nrc.ipSetHandler, err = utils.NewIPSet(false)
```
All other calls to functions in `IPSet` will remain the same, so to switch to ipv6-only should be simple.
For dual-stack all functions calls must go to both an ipv4 and ipv6 instance of `IPSet`. So perhaps it would be better to pass an …
=> Ipv6; Support ipset with "family inet6"

pkg/controllers/netpol/network_policy_controller.go, pkg/utils/ipset.go
Add support for `except` feature of network policy rule.
Solve #326 based on #529 
I have completed the following test cases:
1. Deploy and test network policy rules that do not include `except` rule.
2. Deploy and test network policy rules including multiple `except` rules.
3. Perform a rolling update on kube-router from master to this PR.
=> Add support for 'except' feature of network policy rule

pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/pod_egress.go, pkg/controllers/routing/utils.go, pkg/utils/ipset.go
This PR takes ipv6 support as far as bgp peering for nodes inside the cluster;
```
Peer                AS  Up/Down State       |#Received  Accepted
1000::1:c0a8:101 64512 00:00:37 Establ      |        0         0
1000::1:c0a8:102 64512 00:00:37 Establ      |        0         0
1000::1:c0a8:103 64512 00:00:40 Establ      |        0         0
```
**NOTE**; with this PR ipv6 code is actually used if the nodeIP is recognised as an ipv6 address. Before ipv4 operation was hard-coded.
The CIDR handling does not work yet so the veth devices does not get any (ipv6) addresses. The `kube-bridge` device is howerver assigned an ipv6 address;
```
11: kube-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
inet6 1000::2:b00:301/120 scope global 
valid_lft forever preferred_lft forever …
```
=> Ipv6; BGP peering

docs/developing.md
Hi all.
I found incorrectly variable name in developing guide. `Makefile` has `IMG_TAG` variable,  but the variable is written in this guide as IMAGE_TAG.
This PR changes the variable name correctly.
=> Change IMAGE_TAG -> IMG_TAG in developing guide

pkg/controllers/routing/utils.go
The ipv6IsEnabled() function only checks if the kernel has ipv6 support, not if it is disabled with;
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
```
By trying to open a port on the standard looback address for ipv6 `[::1]:0` a disabled ipv6 is also detected.
This caused #155 to resurface.
=> Improved detect in ipv6IsEnabled()

docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
For ipv6 it is not possible to use the ip address as router-id
and this parameter is required.
There is discussions ongoing on how to handle router-id in an ipv6-only cluster.  For now at least the router-id must be specified using this command line parameter. This keeps the procedure to obtain a router-id outside the `kube-router` binary and allows ipv6 testing to continue.
=> Added "--router-id=" parameter.

docs/bgp.md
Hi, I found typo on https://github.com/cloudnativelabs/kube-router/blob/master/docs/bgp.md .
=> fix typo on docs/bgp.md

pkg/controllers/routing/bgp_peers.go
Use proper conversion so correct cluster ID is passed to GoBGP library. GoBGP was complaining:
```
E1114 19:05:19.722793       1 bgp_peers.go:146] Failed to add node 192.168.56.101 as peer due to route-reflector-cluster-id should be specified as IPv4 address or 32-bit unsigned integer
E1114 19:05:19.723448       1 bgp_peers.go:146] Failed to add node 192.168.56.102 as peer due to route-reflector-cluster-id should be specified as IPv4 address or 32-bit unsigned integer
```
with out this fix as kube-router was passing wrong cluster-id.
Please use `cloudnativelabs/kube-router-git:rr-fix` if you would like to test.
=> Fixes regression in BGP route reflector functionality.

pkg/controllers/routing/bgp_peers.go
This change is to restrict to public and private ranges. As per https://en.wikipedia.org/wiki/Autonomous_system_(Internet)#ASN_Table
=> No reason to restrict Peer ASN's to private only. 

pkg/controllers/proxy/network_services_controller.go
will fix the IPVS low throughput issues
https://github.com/kubernetes/kubernetes/pull/71114
=> make NSC set net.ipv4.vs.conn_reuse_mode=0

pkg/controllers/proxy/network_services_controller.go, pkg/utils/sysctl.go
and add https://github.com/kubernetes/kubernetes/pull/70530/files
=> unified function to set sysctl values 

docs/bgp.md
Using echo places a new-line character at the end of the base64 generated string which will cause the peering to fail for most use-cases as it is unlikely to be present in the configuration of the other peer.
=> docs/bgp.md: change example to use printf

docs/user-guide.md, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/ecmp_vip_test.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go
Fixes #75.
Please let me know if I did something obviously wrong or if there are better/nicer ways to code this.
This is the first go code I ever wrote, I'm a Python programmer at heart.
=> implement per-service annotations to control IP advertisment

pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go
With this PR ipv6 router to pod CIDRs are inserted in the ipv6 routing table;
```
Peer                AS  Up/Down State       |#Received  Accepted
1000::1:c0a8:101 64512 00:00:18 Establ      |        1         1
1000::1:c0a8:102 64512 00:00:17 Establ      |        1         1
1000::1:c0a8:103 64512 00:00:18 Establ      |        1         1
1000::1:c0a8:100/120 dev eth1 proto kernel metric 256  pref medium
1000::2:b00:0/120 via 1000::1:c0a8:103 dev eth1 proto 17 metric 1024  pref medium
1000::2:b00:100/120 via 1000::1:c0a8:102 dev eth1 proto 17 metric 1024  pref medium
1000::2:b00:300/120 via 1000::1:c0a8:101 dev eth1 proto 17 metric 1024  pref med
...
```
Params to `kube-controller-manager`;
```
kube-controller-manager --allocate-node-cidrs=true --cluster-cidr=1000::2:11.0.0.0/112 …
```
=> Make ipv6 routing to pods (CNI routing) work for ipv6

pkg/controllers/routing/network_routes_controller.go
Fix for #588
Adds default forward rules if they was removed
```
-A FORWARD -i kube-bridge -m comment --comment "allow outbound traffic from pods" -j ACCEPT
-A FORWARD -o kube-bridge -m comment --comment "allow inbound traffic to pods" -j ACCEPT
-A FORWARD -o v4 -m comment --comment "allow outbound node port traffic on node interface with which node ip is associated" -j ACCEPT
```
=> Periodicaly sync default forward rules

pkg/controllers/proxy/network_services_controller.go
Traffic coming to IPVS service first goes throught iptables INPUT chain. If iptables policy set to DROP and no INPUT rules added manually to access services they will be inaccessible. This commit adds iptables rule to access IPVS services.
Should fix #602 and somewhat fixes #282
=> Add iptables input rules for ipvs services

pkg/controllers/routing/network_routes_controller.go
https://github.com/cloudnativelabs/kube-router/issues/607
=> Enable net.bridge.bridge-nf-call-ip6tables for IPv6

docs/developing.md
Small note to future developers that kube-router uses dep for dependency management.
=> Add documentation on dependency management using dep.

pkg/controllers/proxy/network_services_controller.go
- on startup create ipsets and firewall rules
- on sync update ipsets
- on cleanup remove firewall rules and ipsets
Fixes #282.
Fixes #613.
=> [RFC] prevent host services from being accessible through service IPs

docs/bgp.md
`peer-router-asns` does not need quotes around
=> Fixed typo in `Global External BGP Peers` example

pkg/controllers/netpol/network_policy_controller.go
This fixes #642, which causes kube-router to crash on valid network policies, and also implements support for ingress and egress rules without a port specified.
The iptable rules created before and after this patch are equivalent when using network policies that specify both port an protocol. When only specifying a protocol, the rules end up looking like this (output from `iptables -S`):
```
-A KUBE-NWPLCY-SXPBPXC4QPX6XLVS -p tcp -m comment --comment "rule to ACCEPT traffic from all sources to dest pods selected by policy name: allow-oracle namespace user-atu" -m set --match-set KUBE-DST-BLGAVYZWLICCYSMQ dst -j ACCEPT
-A KUBE-NWPLCY-SXPBPXC4QPX6XLVS -p tcp -m comment --comment "rule to ACCEPT traffic from source pods to all destinations selected by policy name: allow-oracle namespace …
```
=> Stop crashing when parsing network policies that only specify protocol and not port

pkg/controllers/routing/network_routes_controller.go
This is a bug fix for: https://github.com/cloudnativelabs/kube-router/issues/574
We were seeing cases where the route would stick in the kernel routing table after the NextHop for a given service VIP had changed to a node outside of the host's subnet. This happens because there is a gap in the logic where if the NextHop for a given service is not withdrawn but rather transitions to a Kubernetes node outside the subnet of the current host nothing is done with the previously inserted route.
This PR makes it so that kube-router will cleanup lingering routes at the same point that it also cleans up tunnels when the next hop has transitioned to a node outside the subnet of the current host.
=> cleanup local routes if nexthop moves outside host subnet

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
when use multiple registries for pulling images in container runtime 
we need specify which registry will use exacly
because https://quay.io/repository/cloudnativelabs/kube-router already exists and contains old kube-router image
=> Specify docker.io as registry for multiple registries environment

CONTRIBUTING.md
The links to `user guide` and `developing` are broken. Not sure if they should point to the md file in the repo or to the official docs at `kube-router.io/docs`.
Signed-off-by: Moritz Johner <beller.moritz@googlemail.com>
=> fix docs: broken links in contributing guide

pkg/controllers/routing/network_routes_controller.go
Fixes #640 
@jprukner if you wish to help test please use image `cloudnativelabs/kube-router-git:grpclistenaddr`
=> make gobgp grpc server listen only nodeip and 127.0.0.1

pkg/controllers/routing/network_routes_controller.go
Fixes Issue: https://github.com/cloudnativelabs/kube-router/issues/605
=> Removes IPv6 address insertion from BGP IPv4-only NEXTHOP field

Makefile
The import github.com/docker/libnetwork/ipvs from pkg/controllers/proxy/network_services_controller.go only builds on linux so 'go generate' from %_moq.go target needs to run inside docker when BUILD_IN_DOCKER is true.
Fixes #659
=> Fix 'make test' on osx with BUILD_IN_DOCKER=true

Makefile
Use last path from GOPATH when it has multiple paths without breaking when it has only one path.
Fixes #657
=> Fix ’make test’ when GOPATH contains multiple paths

docs/bgp.md
See #676
Changes of wording are welcome if you know a clearer way to explain this.
=> document workaround for #676

MAINTAINER.md
@jimmy-zh has shown interest to help maintenance of the project. He has done [significant contributions](https://github.com/cloudnativelabs/kube-router/commits?author=jimmy-zh) to NPC.
=> add Jimmy to maintainers

docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
This PR implements PR #371 ideas, keeping the existing behaviour but allowing users to opt in for a full overlay regardless of the subnet the nodes are in
=> Introduces the option --overlay-type={subnet,full}, to be able to always generate IPIP tunnels regardless of node subnets

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
Updated PR - this one also deletes existing *.conf files in cni config directory.  These are some thoughts:
1. This deletes existing *.conf file so it can safely be applied over existing kube-router and it will update the conf format.
2. Although the kubelet only reads the first config in lexicographic order, there doesn't appear to be any limitation in the cni spec itself against having multiple configs.  Therefore, the init container only deletes *.conf files if there was no pre-existing kube-router-installed 10-kuberouter.conflist file.  The assumption is the first install is in a prepared environment, but after that all bets are off.
2. Existing *.conflist or other files are not deleted.  If kube-router is deployed into an environment like this the assumption is that the environment …
=> default cni config to list format

docs/ipv6.md, pkg/controllers/routing/aws.go, pkg/controllers/routing/bgp_peers.go
This commit fixes a grammar mistake in a doc and some log messages.
=> docs,pkgs: change 'can not' to 'cannot'

pkg/controllers/routing/network_routes_controller.go
Current implementation never considers the "kube-router.io/pod-cidr"
annotation when creating an ipset for the node pod network CIDR.
The Node.Spec.PodCIDR is always used instead.
This patch prefers the annotation PodCIDR over the Node.Spec.PodCIDR
=> Prefer node PodCIDR from an annotation

pkg/controllers/routing/network_routes_controller.go
@murali-reddy @lucasmundim 
In the wake of #666 we removed some returns from the route/tunnel cleanup process of the `injectRoute` function in order to facilitate the `--overlay-type=full` option. However, these returns were what prevented routes and tunnels from being created when `--enable-overlay=false` was specified.
As such, kube-router will now make IPIP tunnels and route traffic to them regardless of whether `--enable-overlay=true` or not. This PR facilitates both functionalities by choosing to return ONLY if overlays have been disabled.
In other words:
* `--enable-overlay=false` - means that tunnels and routes to those tunnels will be cleaned and NOT created no matter how `--overlay-type` is set
* `--enable-overlay=true` - IPIP tunnels and routes to those tunnels will be created …
=> Correct ipip Always On

pkg/controllers/routing/network_routes_controller.go
handle case when `route *netlink.Route` is not set in `injectRoute`
=> handle null *route

.travis.yml, Makefile, build/travis-deploy.sh
Closes: #622 #591
I tried to understand the build and push process and adapted it so it should push and build multiarch.
Added the `push-manifest` in the makefile, it uses the [estesp/manifest-tool](https://github.com/estesp/manifest-tool) to push the manifest for the release and latest tag.
It should work but I haven't test it :)
=> First stab at pushing multiarch releases

pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go
@murali-reddy I finally got around to making good on an implementation for #633 based on your recommendation.
The main goal of this request is to add a BGP import policy that rejects cluster VIPs so that they don't get added to the local routing table and instead are routed via pure ECMP.
In the process of doing this, I found that there was quite a bit of logic crossover between the export policies and the import policies (all of the prefixset and neighborset stuff). So rather than duplicate the logic or make the function larger than it was already I broke `addImportPolicies` and `addExportPolicies` into their own functions. This makes it easier to read and identify them as separate functionality. They are now called from a new `AddPolicies` function that first sets up the common prefix …
=> Add Import Policy for Service VIPs

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go
In reference to issue #725, we modified kube-router to send
heartbeats during policy sync to prevent missing heartbeats
while running iptables commands.
This commit is the first part to make kube-router faster and
more robust when applying network policies.
Signed-off-by: Jérôme Poulin <jeromepoulin@gmail.com>
=> Send heartbeats during NetworkPolicy and NetworkService sync.

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
Fixes https://github.com/cloudnativelabs/kube-router/issues/758
Also had to add a selector for this to work for me (k8s version 1.14.3)
=> update to apps/v1 and add selector

docs/user-guide.md, pkg/cmd/kube-router.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
GoBGP default value for deferral time is 360 seconds. That means that the
routes are not sent to the BGP peer until this timer is elapsed.
We painfully noticed this when we restarted kube-router in our cluster. The pod routes were first stale on the routers. After they expired it took some more minutes until they were updated again. The pods and services on the node were not reachable during this time. We also were hit hard by https://github.com/cloudnativelabs/kube-router/issues/725, which caused regular kube-router restarts.
=> Allow setting the BGP graceful restart deferral time. See RFC4724 4.1

pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/network_routes_controller_test.go
This patch is a fix for each kube-router to properly originate `clusteripprefixset` (next-hop-self) injected by controller while still rejecting to import the same NLRI advertised from peers, so it can export the originated paths to eBGP peer(s). 
- without this patch:
```
Name kube_router_import:
StatementName kube_router_import_stmt0:
Conditions:
PrefixSet: any clusteripprefixset
Actions:
reject
```
- with this patch:
```
Name kube_router_import:
StatementName kube_router_import_stmt0:
Conditions:
PrefixSet: any clusteripprefixset
NeighborSet: any allpeerset
Actions:
reject
```
=> fix clusteripprefixset import policy

pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/ecmp_vip_test.go
This fixes an issue where when a service is removed from Kubernetes, a BGP withdrawal UPDATE is never sent. Export policies are modified to prevent the routes from appearing in `adj-out`, but they are still present in the RIB.
The root of the issue is that `toAdvertise` and `toWithdraw` are incorrectly computed in `getVIPsForService` for deleted services. This PR corrects that logic.
=> Fix: Send BGP Withdrawals for Service VIPs Upon Service Deletion

cni/10-kuberouter.conf
set `cniVersion` in `cni/10-kuberouter.conf`. `cnvVersion` is required in kubernetes 1.16 and is already set in all the manifests in the daemonset directory.
=> set cniVersion in 10-kuberouter.conf

pkg/controllers/netpol/network_policy_controller.go
For very busy tcp connections there is a small possibility to receive
a TCP RST during the iptables sync. It happens only when `--run-firewall=true` is set.
In function `NetworkPolicyController.syncPodFirewallChains` a default `REJECT`
rule is chronologically added before the accept-`RELATED,ESTABLISHED` rule for ingress and
egress connections. In between of the creation of these two rules a connection reset can happen for already established connections.
The solution is to add the allow-`RELATED,ESTABLISHED` rule before the `REJECT` and
jumps to this iptables chain. I see no reason the `REJECT` rule is inserted before the `ACCEPT` rule,
but maybe I miss something.
=> Fix connection resets during firewall sync

pkg/controllers/proxy/network_services_controller.go
Currently we can have error on service proxy if we cannot set sysctl (in my case), but those errors are return and not shown. Just show them, like other controllers.
I found this error by running service proxy as daemonset like we did for the network part. It's very annoying to have a silent fail on that part. Instead continue because we can set sysctl on the host part directly
=> [FIX] Don't ignore silently service proxy errors.

.goreleaser.yml
go releaser failing with error `field archive not found in type config.Project` chaning it to `archives`
=> fix .goreleaser.yml

pkg/controllers/proxy/network_services_controller.go
This disambiguates masqueraded source ip when a container with hostNetwork=true and dnsPolicy=ClusterFirstWithHostNet on as host with multiple interfaces or ip alias on loopback interface tries to access a pod behind an IPVS service.
It also deletes the old rule so it won't break when upgrading. 
Fixes #549 and Fixes #667
=>  Use SNAT instead of MASQUERADE to source NAT outbound IPVS traffic

docs/user-guide.md, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/options/options.go
Add a `--service-cidr` argument and ignore deletion of IPVS rules not in the service cidr.
Fixes #829
=> Ignore deletion of unknown IPVS rules

pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/pbr.go
The pods still work when api server is down, so need kube-router pod not be restart with live probe enabled. 
https://github.com/cloudnativelabs/kube-router/issues/810
=> fix unhealthy on api server down

pkg/controllers/routing/network_routes_controller_test.go
fixes test failures due to change in #813 in which we just read pod CIDR from the node object just once at the begining
=> populate pod CIDR in tests using network routing controler

.gitignore, Makefile, build/travis-deploy.sh
We are running an environment mixed with amd64 and ppc64le machines.  Including ppc64le builds in the official multi-arch builds would be helpful.  Thanks!
=> Enable ppc64le builds

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go
Currently only endpoint IP used so any change in port of the endpoint leaves stale ipvs server config. With this change (ip, port) tuple is used to track active endpoitns of service and to identify stale IPVS config of server of a service
also service info that is built does not carry `targetport` info, so any change to just `targetPort` in service spec was not trigerring sync
Fixes #841
=> use endpoint (IP, port) tuple to track active endpoints of a service 

pkg/controllers/routing/aws.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go
Fixes #862
this PR removes last and very few instances where API objects were directly read from the API server
=> read the necessary API objects from local cache instead of listing from the API server

pkg/controllers/netpol/network_policy_controller.go
While --set is still ambiguous it can clash with other module options, so it is better to be more specific and use the --match-set option. This also more closely aligns with all other areas of the code that already use --match-set.
From iptables-extensions man page:
The option --match-set can be replaced by --set if that does not clash with an option of other extensions.
=> switch --set to less ambiguous --match-set

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/ecmp_vip.go
in DeleteFunc handlers across the controllers handle the case where received object can be of type DeletedFinalStateUnknown
fixes one of the symptoms (panic on receiving DeletedFinalStateUnknown objects) reported in #712
=> handle DeletedFinalStateUnknown objects in DeleteFunc handlers

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go
Updates to selector matching to allow for selectors other than just matchLabels.
https://github.com/cloudnativelabs/kube-router/issues/614
@aauren @mrueg
=> Update selectors to Allow matchexpressions Fixes #614

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/network_services_controller_moq.go, pkg/controllers/proxy/network_services_controller_test.go, pkg/controllers/proxy/service_endpoints_sync.go
10800 secs (5 hours) is hardcoded for ipvs when ClientIP is set for SessionAffinity for a service. The value of "service.spec.sessionAffinityConfig.clientIP.timeoutSeconds" should be used to set the timeout instead.
=> honor the ClientIP session affinity timeout when set. 

pkg/controllers/proxy/network_services_controller.go
The behavior of iproute2 changed in 5.0 as described in #750: now if a
table has not been created, `ip route list table <table>` will produce a
non-zero exit code.
It's not really needed to check tables via `list` anyway, since they
will be created by iproute2 when needed on first use. So relax error
handling for `ip route list table`, and remove it completely when a
table might be missing.
This fixes #750
=> Handle missing routing tables

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
I believe this `fixes` this issue:
https://github.com/cloudnativelabs/kube-router/issues/675
=> Enabling --bgp-graceful-restart by default when the router component is deployed via daemonset

Dockerfile, Makefile
Currently we have a arch-specific binary that gets installed on an amd64
container. This change ensures that the container image matches the
arch-specific binary.
Using alpine archictecture-specific images as  mentioned under
https://hub.docker.com/_/alpine
To support architectures different from host architecture, this uses
qemu-static.
=> Add multi-arch support for container images.

docs/Observability.md, pkg/controllers/netpol/network_policy_controller.go
logged packets can be further by read by ulogd
Fix only works with kernel > 4.11 please see https://github.com/cloudnativelabs/kube-router/issues/505#issuecomment-619633699
Fixes #505
=> nflog the packet that will be dropped by network policy enforcement

Makefile, build/travis-deploy.sh
Fixes #887 
* Publishes multi-arch and manifest images on master push.
=> push multi-arch images to the dev registry

pkg/controllers/netpol/network_policy_controller.go
- outbound traffic from pod should be intercepted in filter table INPUT chain (pod's traffic that is destined to node's local ip). with out this fix even with network policy to drop all egress traffic, pod can reach host IP's. Pod's can access any service hosted in host network as well
~~- rules to permit forwarding pod traffic should be appended at the end to the FORWARD chain. In some distro's default policy for FORWARD chain is drop. So explicit rule must be added in FORWARD chain for the traffic from the pods. These rules should be lower order than any network policy chains~~
removing the changes to network routing controller to append the rule to enable forwarding from the pods. Will address in seperate PR
=> fixes egress network policy enforcements

pkg/controllers/proxy/network_services_controller.go
ensure heartbeats are sent when performing sync in both the cases of  periodic sync and on add/delete/update evernts corresponding to services and endpoints
this change just moves sending the hearbeat to method `syncIpvsServices` that is common method that is invoked in all cases.
Fixes #879
=> service proxy: ensure hearbeats are sent during sync

.gitignore, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go
FYI @murali-reddy @mrueg @filintod 
This is a fix for: #795 
This change does two things broken up by commit:
1) Converts networkPoliciesInfo to be a function variable rather than a variable on the npc struct. Through extensive testing I've found that this gives a relatively small memory performance gain, but still worth doing IMO since this variable isn't referenced outside of the Sync function and its dependency functions. Converting the variable allows the GC to free up cached data sooner.
2) Converts the `Sync()` method to use semaphores and converts all handlers to call the function asynchronously. Pausing the handler flow and waiting for the Sync method to finish is causing the k8s watchers to backup and hold on to pod, network policy, and namespace object metadata until the …
=> Fix Memory Consumption in network_policy_controller

pkg/controllers/routing/ecmp_vip.go
@murali-reddy This goes towards fixing another rare, but outstanding bug with kube-router for the 1.0.0 release.
While rare that NodeName is missing it is not guaranteed to exist by the Kubernetes API (see link below). This retains checking via NodeName first if it exists, but if it's nil rather than segfaulting it evaluate via IP address.
Fixes #781
https://github.com/cloudnativelabs/kube-router/blob/master/vendor/k8s.io/api/core/v1/types.go#L3487
=> fix(ecmp_vip): check for nil nodename

pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/network_routes_controller.go
@murali-reddy This goes towards fixing another rare, but outstanding bug with kube-router for the 1.0.0 release.
Before we used to raise an error when a node was missing an IP, but it turns out that this is not a required attribute of a node. And while it is rare that a node would be missing an IP address, a node doesn't require an IP address or a name or really much of anything in order to
exist.
This brings us to stronger conformance with the Kubernetes API and makes it so that kube-router logs errors rather than changing it's health status and potentially causing cascading failures across the fleet if a user adds a node like this.
Properly fixes #846
=> fix(network_routes): missing node ip -> error log

Dockerfile
Updated dockerfile to make use of alpine 3.11. Currently 3.9 version in dockerflle becomes end of life in November.
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
=> Dockerfile: Update to alpine:3.11

.golangci.yml, Makefile, build/travis-test.sh, cmd/kube-router/kube-router.go, cmd/kube-router/kube-router_test.go, pkg/cmd/kube-router.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_service_graceful.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/network_services_controller_test.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/routing/aws.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go, pkg/healthcheck/health_controller.go, pkg/metrics/metrics_controller.go, pkg/utils/ipset.go, pkg/utils/node.go
This adds support for golangci-lint to improve code quality https://github.com/golangci/golangci-lint
=> Add golangci-lint support

pkg/controllers/netpol/namespace.go, pkg/controllers/netpol/network_policy_controller.go
we should sync firewall if namespace labels change, beacause some network policy maybe use namespace selector, and I move namespace code to namspace.go.
=> network_polixy: full sync when namespace labels change

pkg/controllers/netpol/network_policy_controller.go
This is the original design (#185) I had in my mind for network policies implementation. Should have been fixed much earlier. 
- adds one level of indirection. No logic change in sync of pod, network policy chains and cleanup of state chains, ipsets etc
INPUT   -> KUBE-ROUTER-INPUT
FORWARD -> KUBE-ROUTER-FORWARD
OUTPUT  -> KUBE-ROUTER-OUTPUT
- easy to troubleshoot with namesake custom chains
```
// Creates custom chains KUBE-ROUTER-INPUT, KUBE-ROUTER-FORWARD, KUBE-ROUTER-OUTPUT
// and following rules in the filter table to jump from builtin chain to custom chain
// -A INPUT   -m comment --comment "kube-router netpol" -j KUBE-ROUTER-INPUT
// -A FORWARD -m comment --comment "kube-router netpol" -j KUBE-ROUTER-FORWARD
// -A OUTPUT  -m comment --comment "kube-router netpol" -j …
```
=> avoid adding kube-router specific rules to enforce network policies in built-in chain used in fitler table

docs/user-guide.md, pkg/cmd/kube-router.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/options/options.go
Fixes #905
Following rules will be prepended in `KUBE-ROUTER-INPUT` chain. So traffic to cluster IP's and node port services are targetted to `RETURN`.
```
Chain KUBE-ROUTER-INPUT (1 references)
pkts bytes target     prot opt in     out     source               destination         
0     0 RETURN     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* allow LOCAL traffic to node ports */ ADDRTYPE match dst-type LOCAL multiport dports 30000:32767
0     0 RETURN     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* allow LOCAL traffic to node ports */ ADDRTYPE match dst-type LOCAL multiport dports 30000:32767
15  1464 RETURN     all  --  *      *       0.0.0.0/0            10.96.0.0/12         /* allow traffic to cluster IP */
0     0 …
```
=> whitelist traffic to cluster IP and node ports in INPUT chain to bypass netwrok policy enforcement

pkg/controllers/netpol/network_policy_controller.go
- change ACCEPT to RETURN with mark when a netpol is matched so that we run through
all the applicable network policies for a flow
Fixes #916
=> run through all applicable network policies for a flow

pkg/controllers/proxy/service_endpoints_sync.go
The `setupExternalIPServices()` function fails due to blindly calling `fmt.Sprint` on the return values of `generateFwmark()`, ignoring the fact that 2 values are returned. This results in errors like the following:
```
E0614 14:03:47.293710       1 service_endpoints_sync.go:343] Failed to verify and cleanup any mangle table rule to FMWARD the traffic to external IP due to Failed to cleanup iptables command to set up FWMARK due to running [/sbin/iptables -t mangle -C PREROUTING -d {REDACTED} -m tcp -p tcp --dport 80 -j MARK --set-mark 4951 <nil> --wait]: exit status 2: iptables v1.8.3 (legacy): MARK: trailing garbage after value for option "--set-mark".
```
This patch corrects this issue.
=> fix unintentional Sprint of two-argument generateFwmark() call

Makefile
Git allows slashes in branch names, but they are not valid in docker tags. This trims slashes from the git branch name so that `make` doesn't fail if they exist.
=> Makefile: remove slashes from git branch if they exist

docs/user-guide.md
Adding documentation with links to upstream to address questions about proxy, SNAT traffic, and network policy.
Helps to better document issues raised in: https://github.com/cloudnativelabs/kube-router/issues/744
=> doc(user-guild.md): add info about proxy and SNAT

pkg/controllers/proxy/network_services_controller.go
=> stop processing service and endpoints updates if network service controller has already shutdown

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
This PR sets tolerations:
```yaml
tolerations:
- effect: NoSchedule
operator: Exists
- key: CriticalAddonsOnly
operator: Exists
- effect: NoExecute
operator: Exists
```
fixes https://github.com/cloudnativelabs/kube-router/issues/821
=> fix tolerations for >1.16

cmd/kube-router/kube-router_test.go, docs/user-guide.md, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
In some scenarios, the holdtime of BGP needs to be adjusted.
(1) If you want the BGP neighbor route to disappear as soon as possible after the kube-router goes down, you should set the holdtime to be smaller.
(2) In some scenarios, after the kube-router goes down, the pod network is normal and can still communicate with the outside world. You want BGP neighbor routing to last longer, so in this case you can set the holdtime to be larger.
=> The bgp-holdtime function parameter of setting holdtime is added to adjust the holdtime of BGP negotiation with the connected network devices.

pkg/controllers/proxy/network_services_controller.go
@murali-reddy this is a small fix for #910
We weren't checking the equality for `persistentTimeout` as part of checking to see if the persistence settings needed to be updated in the IPVS service.
I also removed a double handling of the ipvs flag changes.
=> fix(nsc): update IPVS svc when timeout changes

pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go
The type of bgpClusterID field was changed to string in order to hold IPv4 and integer string representations from the annotations.
When parsing of the integer cluster if fails, IPv4 parsing will be attempted before exiting with error.
=> Allow to configure RR cluster id using IPv4 strings

Dockerfile
When localhost is used as the cluster server in kubeconfig, it cannot be resolved due to missing /etc/nsswitch.conf in the image. https://github.com/kubernetes-sigs/kubespray/issues/6175 is caused by this issue.
A common workaround is to add `echo "hosts: files dns" > /etc/nsswitch.conf` in Docker file as mentioned by https://github.com/golang/go/issues/22846#issuecomment-380809416.
=> add /etc/nsswitch.conf in Dockerfile

.goreleaser.yml
goreleaser was missing ldflags, so the binaries produced and added to
the release did not include version information.
=> .goreleaser.yml: Add LDFLAGS

docs/user-guide.md, pkg/options/options.go
@murali-reddy 
In Slack the presence of this option confused a user that tried to use it to set their cluster-cidr instead of setting it on `kube-controller-manager`. I didn't realize that we still had this option around any longer, but it looks like it's functionality was ripped out here: https://github.com/cloudnativelabs/kube-router/pull/111 but then the option was never removed, so now users can set it, but it's effectively a no-op.
=> fix(options): remove deprecated cluster-cidr option

Gopkg.lock, Gopkg.toml, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/pod_egress.go, vendor/github.com/coreos/go-iptables/NOTICE, vendor/github.com/coreos/go-iptables/iptables/iptables.go
To mitigate conntrack issues in Kubernetes.
See: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02 and kubernetes/kubernetes#56903 for details.
=> Add --random-fully to MASQ iptables rules to mitigate conntrack issues

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
@murali-reddy @aauren I would suggest to set up Issue Templates in Github as in https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates these would allow us to gather important information in the initial issue report (e.g. kube-router version, kubernetes version, deployment type, size of cluster)
See also:
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
Unfortunately, I lack permission to set it up in the settings page as mentioned in above docs. @murali-reddy can you take a look and maybe set it up yourself?
=> Setup Issue Templates

pkg/options/options.go
I was about to add another option and before I did so figured that I would clean up our existing options. I've always found it hard to navigate these without constantly searching because I could never consistently find what I was looking for. I sorted the struct fields by name and I sorted the CLI parameters by their name. Hopefully that makes sense to everyone.
=> Sort Options

pkg/controllers/proxy/service_endpoints_sync.go
When creating externlIP service with DSR tunnel, I got the following error log, and kube-router failed to create the related IPVS tunnel.
> 0813 23:38:37.465953 1642001 network_services_controller.go:1762] Successfully added service: TCP:<nil>:80 (Flags: )
> E0813 23:38:37.469536 1642001 service_endpoints_sync.go:313] Failed to delete external ip adress from dummyVipInterface due to cannot assign requested address
This is because when the externalIP service is created for the first time, the externalIP didn't exist on the dummy interface before, the `nsc.ln.ipAddrDel` call above my change would result in IfaceHasNoAddr error, preventing `routeVIPTrafficToDirector` function below to create the IPVS tunnel. Therefore, the IfaceHasNoAddr error should be ignored.
=> add IfaceHasNoAddr check for external ip delete error

.github/ISSUE_TEMPLATE/bug_report.md
This adds a kube-router parameters section to the bug report issue template to better help us understand the way in which users are running kube-router at the time when it encounters an issue.
=> feat(bug_report.md): add parameters section to bug report

docs/user-guide.md, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/options/options.go
This PR contains a couple of things:
1) Parse ClusterIP service range CIDR as a CIDR instead of as a string before passing it to iptables
2) Parse and validate NodePort ranges before before passing it to iptables
3) A side-effect of the above is that we can now allow ranges specified with a hyphen as well as the of the iptables colon `8080-8090` vs `8080:8090`. The hyphen form is a more k8s cohesive way to specify the NodePort range as it's the same format that kube-apiserver uses
4) Added support for defining ExternalIP ranges which addresses the problem found in #934 
5) I added unit tests for all of the above
=> Permit ExternalIP on input

docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
This is an update to the PR previously submitted by @jraby in #800, it just needed some rebasing (since the options.go file has changed significantly since he previously submitted) and some extra linting.
This is based on #982 and is meant to be merged after that is merged into the master branch. I've verified that it builds and that all unit tests are currently passing. Additionally, I've deployed into a test cluster and verified the password file functionality.
This is the last PR needed to satisfy issue #794
=> Add Support for Reading Peer Passwords via a File

pkg/controllers/netpol/network_policy_controller.go
This PR changes the way we manage marks in the NetworkPolicyController by applying a mask so that we only reset our FW mark as part of the FW chain and leave the other marks that may exist on the packet alone.
Ever since kube-router v1.0.0-rc5 we've been resetting all marks on the packet whenever the pod has a network policy applied to it as part of the new MARK and RETURN flow which allows traffic to traverse all relevant network policies instead of being ACCEPT'ed after hitting the first match rule.
However, there are other systems in kube-router and in the CNI subsystems which also apply marks. When the packet is traversing a firewall chain that is applied by the NPC, it goes through like this (using FORWARD as an example here):
1) `FORWARD` -> `KUBE-ROUTER-FORWARD`
2) …
=> fix(network_policy): mask mark reset on FW marks

docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/utils.go, pkg/options/options.go
set `mtu` in cni spec to auto configure MTU's of the pod's veth's and kube-bridge interfaces
simple approach to pick the MTU associated with interface associated with node's IP as MTU. This should work fine for most cases.
Please see https://github.com/containernetworking/plugins/tree/master/plugins/main/bridge#network-configuration-reference for further details on how `bridge` CNI works
Fixes #165
=> auto configure MTU

pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/ecmp_vip_test.go, pkg/controllers/routing/network_routes_controller_test.go
LoadBalancer was not advertising externalIPs in services, this fixes it.
Fixes: https://github.com/cloudnativelabs/kube-router/issues/994
=> Add LoadBalancer to getExternalIPs

.gitignore
This was likely required for old-style vendoring and shouldn't be
necessary for the current version of kube-router
@murali-reddy
=> .gitignore: Drop vendor folder

pkg/controllers/proxy/network_services_controller.go
We had some stale IPs in table 79 that gave me quite the headache.
Currently, any `externalIP` is added to the `activeExternalIPs` map, while only DSR `externalIP`s are added to the routing table. Only routes for deleted `externalIP`s will be removed from the table afterwards. `externalIP`s that no longer carry the DSR annotation will remain.
This PR updates the `activeExternalIPs` map to carry only those IPs that we are also actively enforcing routes for.
=> Cleanup non-DSR externalIPs

pkg/controllers/netpol/namespace.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go
Cleaning up the network policy code
NetworkPolicy in the extensions/v1beta1 API version is no longer served
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
=> remove deprecated netpol beta API support

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml
rbac.authorization.k8s.io/v1 is stable since 1.8, updating
it avoids warnings when applying the manifests on recent versions
of Kubernetes (v1.19+).
Signed-off-by: lcavajani <lcavajani@suse.com>
=> Update RBAC apiVersion from v1beta1 to v1

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go, pkg/utils/ipset.go
This PR updates `kube-router` to use `ipset restore` instead of calling `ipset add` multiple times in a row. This significantly improves its performance when working with large sets of rules.
For me, with ~2K ClusterIP services in a minikube cluster, this improves the `syncIpvsFirewall()` speed from ~3.5s to ~0.3s.
Ref: https://github.com/cloudnativelabs/kube-router/issues/962
=> Improve ipset performance with large sets

docs/bgp.md
As a result of the work added in https://github.com/cloudnativelabs/kube-router/pull/106, nodes that are not layer 2 adjacent will use IPIP tunnels to communicate to each other. While testing a cluster spanning multiple networks, I found that things worked properly, but was concerned about this line in the docs. Looking at git history, this line predates kube-router's ability to run across multiple networks using IPIP tunnels. I suspect this line is no longer correct, and should be removed from the docs.
=> It appears as though this line is no longer relevant

docs/bgp.md, pkg/controllers/routing/network_routes_controller.go
Since both IPIP/tunnel and overrride-nexthop have their own parameters to enable/disable, it's better to make the switch independent each other. This PR is needed to support the case where both cross subnet iBGP peering (via tunnel) and multiple upstream routers peering(via override-nexthop) feature are needed.
=> Making IPIP/tunnel and override-nexthop independent

Makefile, cmd/kube-router/kube-router.go, pkg/cmd/kube-router.go, pkg/metrics/metrics_controller.go, pkg/version/version.go
This should add build_info metrics that can be consumed by prometheus to identify which version of kube-router is running.
=> metrics: Add build_info metrics

pkg/cmd/kube-router.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/pod.go, pkg/controllers/netpol/policy.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/routing/network_routes_controller.go, pkg/metrics/metrics_controller.go, pkg/utils/ipset.go, pkg/utils/iptables.go
replace all individual iptables command that are run during full network policies sync into `iptables-save` and `iptables-restore`
This PR is intend to replace #1010
In #1010 I tried to refactor the code so that on pod add/delete/update kube-router performs iptables, ipset updates that are only constrained to corresponding pod. However after spendig time refactoring code it truned out it is not right approach.
In general kube-router should stick to `level-triggered` sync (Please see [1] [2]) i.e.) consider whole current state and desired state as a whole. 
Please use the image `cloudnativelabs/kube-router-git:amd64-iptables-save-restore` if any testing.
[1] https://speakerdeck.com/thockin/kubernetes-controllers-are-they-loops-or-events?slide=38
[2] …
=> use iptables-save and iptables-restore for npc sync

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/ecmp_vip.go, pkg/utils/service.go
Fixes #978 
The main purpose of this PR is to make the network_routes_controller and network_services_controller more performant by detecting when services (or related endpoints) are headless and stop processing early.
In both NRC and NSC we are only concerned with VIPs and endpoints related to those VIPs. Since headless services have neither we can save a lot of extra cycles if we catch creates, updates, and deletes of headless services and make them a noop.
This PR also:
* Adds some extra comments around confusing logic
* Removes a superfluous call to AddPolicies
* Adds the logging statement back to tryHandleServiceDelete
=> Handle headless services

pkg/controllers/netpol/policy.go
[deprecated]support pod's label changes :   https://github.com/cloudnativelabs/kube-router/issues/1035
support networkpolicy that egress to namedport without dst-address: https://github.com/cloudnativelabs/kube-router/issues/1036
=> support networkpolicy that egress to namedport without dst-peer

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/ecmp_vip.go, pkg/utils/pod_cidr.go, pkg/utils/service.go
Avoiding these error in logs:
```
E0324 09:08:52.400573       1 network_services_controller.go:817] failed to convert endpoints resource to service: service resource doesn't exist for endpoints: "e2e-test-crd-conversion-webhook"
E0324 09:09:45.440330       1 network_services_controller.go:817] failed to convert endpoints resource to service: service resource doesn't exist for endpoints: "csi-hostpath-attacher"
E0324 09:09:46.041111       1 network_services_controller.go:817] failed to convert endpoints resource to service: service resource doesn't exist for endpoints: "csi-hostpathplugin"
E0324 09:09:46.477222       1 network_services_controller.go:817] failed to convert endpoints resource to service: service resource doesn't exist for endpoints: "csi-hostpath-provisioner"
E0324 …
```
=> skip logging Error when there is no Service object for an Endpoint

docs/user-guide.md, pkg/controllers/proxy/network_services_controller.go
Hello,
This pull request add support for externalIps hairpin rules, via an annotation on service in order to add extra NAT rules only when requested.
My use case is the following, I have a Consul server on K8S and exposed to hosts outside the cluster via an external IP. The server is configured to advertise the external IP instead of the pod one (or clusterIP), to let other Consul agent gossip with him, even if they're outside the K8S cluster.
Until now, there no problem, but the Consul server periodically check other servers, including himself, as part of the Consul autopilot feature and the lack of hairpin NAT rules for externalIPs make this self-check fail with a timeout.
=> Add hairpin support for externalIps

.github/workflows/codeql-analysis.yml
See also: https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning
Configuration taken from: https://github.com/github/codeql-action/blob/main/README.md#usage
=> .github: Add codeql scanning action

pkg/utils/ipset.go, pkg/utils/ipset_test.go
There is a bit of a bug in kube-router, which only seems to exist since 1.2.x — since the implementation was changed to use `iptables-restore` and friends. Essentially, the generated IPSets are observably empty/incomplete for a brief moment between the `flush` and the completion of all the `add`s provided to `ipset restore`. This causes inbound or outbound connection failures for ingress/egress networkpolicies, respectively.
After some [discussion in slack,](https://kubernetes.slack.com/archives/C8DCQGTSB/p1618429634057500) here's a PR.
This PR uses an approach discussed [on the netfilter mailing list](https://netfilter.vger.kernel.narkive.com/tJsj5nGC/ipset-save-and-restore) to avoid this problem by creating new sets and swapping them into place. 
1) a temporary set is created of the …
=> Swap temporary IPSets during ipset restore

pkg/controllers/proxy/network_services_controller.go
Switches the endpoint map comparison in OnEndpointsUpdate from being a DeepEqual, to instead checking that all services exist, and that their associated endpoints are similar.
Ordering is no longer considered important in regards to the IPVS update check.
Should fix #1026 - got an image up on `ananace/kube-router-test` that seems to be doing well in regards to that
Not sure if there's a better way to do this, as I'm not really a Go coder - but the issue seemed simple enough to fix
=> Fix overly eager IPVS updating in network services controller

pkg/controllers/netpol/pod.go
Fixes #1067 
existing KUBE-POD-FW rules for any host network pods will be automatically cleaned up on first sync.
=> skip hostnetwok pod's from enforcing network policies

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/utils.go, pkg/controllers/netpol/utils_test.go
FYI @mrueg @murali-reddy
NodePort ranges don't parse correctly, because they are parsed as signed integers which means that the max port is incorrectly determined to be `32,766` when in actuality it is `65,535`. This PR fixes that by changing the int conversion function from `ParseInt` to `ParseUint`. Also separates logic so that it can be tested more easily, and adds unit tests to make sure there is no regression.
Fixes #1083
=> fix(NPC): parse NodePorts as unsigned ints

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/network_services_controller_moq.go, pkg/controllers/proxy/network_services_controller_test.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/utils.go, pkg/utils/node.go
Heavily based on #769, but replaces as #769 was based on kube-router's older code that set MTU statically. Since kube-router 1.1.X, we've had the ability to automatically set the MTU for kube-bridge based upon the primary interfaces MTU setting.
So, I moved `GetMTUFromNodeIP()` up a few layers and utilized the logic for figuring out how to set the TCPMSS.
Fixes #630
=> Set DSR TCPMSS Based on Link MTU

Dockerfile, build/image-assets/iptables-wrapper-installer.sh
This adds the upstream iptables-wrapper script from upstream to intelligently select which version of iptables to use based upon the host system as well as where other iptables entries have been added already (so that they don't become out of order).
See https://github.com/kubernetes-sigs/iptables-wrappers for more information
Fixes: #1058
=> feat(iptables): add upstream wrapper script

.github/dependabot.yml
See also: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
@aauren @murali-reddy this enables dependabot to manage and updates golang dependencies once per week. It will send PRs with suggested updates.
=> .github: Enable dependabot to manage dependencies

pkg/cmd/kube-router.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/controllers/netpol/policy.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go
Potential fix for #1081 
I'm marking this as a WIP as I'm not 100% sure that this is what's causing a problem, but at this point I highly suspect that there is contention between ipset invocations within the different controllers. Especially since most of the periodic syncs happen right on top of each other (by default the 5m period syncs are on a ticker that end up being scheduled within milliseconds of each other).
I suspect that what happens is that on some starts when the timing of the periodic syncs is incredibly unlucky, the controllers end up executing something like this:
1. NPC takes a snapshot of the system’s ipset state: https://github.com/cloudnativelabs/kube-router/blob/96675e620be3e0c152d5b873146cc2f7f54c9429/pkg/controllers/netpol/policy.go#L83
2. NPC …
=> Add Locking Around ipset Invocations

pkg/controllers/netpol/pod.go, pkg/controllers/netpol/policy.go, pkg/controllers/netpol/utils.go, pkg/controllers/netpol/utils_test.go
This has a couple of changes in it that make kube-router's NetworkPolicy handling better:
1. Don't process policy for pod statuses that are `Completed`, `Succeeded`, or `Failed`. This changes kube-router to match what other network plugins do (e.g. https://github.com/projectcalico/libcalico-go/blob/9bbd69b5de2b6df62f4508d7557ddb67b1be1dc2/lib/backend/k8s/conversion/conversion.go#L157-L171 thanks @chendotjs). Additionally, this fixes the issue reported in #1056 where errors were caused because the CNI will re-use the Pod IP address of pods in these phases which can improperly apply NetworkPolicy to pods that should be without it.
2. Don't process new pods (i.e. ones going through `AddFunc()`) if they are missing their PodIP, are in an invalid phase ^^^, or are …
=> Make Pod NetworkPolicy Handling More Efficient / Correct

.goreleaser.yml
@mrueg 
This should have been included in #1031 as without this, published binaries made by goreleaser don't print build version/date correctly.
=> fix(goreleaser): add version and date to published binaries

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/controllers/netpol/policy.go
This PR adds support for the recently added endPort field in kubernetes, which now is feature gated but will be marked as default in next release.
TODO:
=> Add support for kubernetes endport field

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/pod.go
add logic in network policy controller to explicitly ACCEPT traffic from/to the pod in both cases
- ACCEPT traffic from the pod is permitted by applicable network policies. 
- ACCEPT traffic if there are no network policies appicable to the traffic
`0x20000` will be used to mark the traffic from/to the pod that matches above cases.
Rule is appened in kube-router's top level chain to  `ACCEPT` traffic if packet is marked `0x20000` 
Fixes https://github.com/cloudnativelabs/kube-router/issues/984
=> add logic to explicitly ACCEPT traffic from/to the pod

Dockerfile, pkg/utils/iptables.go
update alpine image to 3.14 which has latest version of `iptables-restore` command with `--wait` option.
Also check if the `iptables-restore` has the wait option (to cover previous vesion of command with no --wait option) and use it
=> use wait option of iptables-restore when available

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go
@murali-reddy this is similarly rough to the mutex locking that I did around ipset operations. My goal would be that once we rework the controllers to have unified ipset and iptables calls from all controllers that this code would go away or at least be rafactored into something else.
However, for the time being, this will fix #1126 by checking for nil's before attempting to call the mutex. I went with this approach because while nothing else uses these `Cleanup()` methods other than `--cleanup-config`, I figured it was better to not count on that in case someone ever changed to code to call them from a running controller and without the mutex present it caused a data layer issue.
=> fix: add nil checking to ipsetMutex cleanup actions

pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/utils.go
@murali-reddy / @mrueg - I was originally setting out to fix #973 but as I got into the code I realized that it desperately needed to be refactored. So I did the refactoring first, mostly extracting methods to make the logic flow a little easier to read. However, I also made it a bit more performant as well by processing withdrawals first.
This also contains a fix for #973 by checking at path withdrawal time whether the reason for the withdrawal is because the peer is unestablished. If the peer is no longer established, then it attempts to clean up the tunnels as well as the routes. I found in my testing that when the tunnel was deleted the system also seemed to automatically clean up the routes that were in table `77`.
@murali-reddy I only did a small amount of local testing as we don't …
=> Fix and Refactor Inject Route

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go
Remove metrics for IPVS services when the IPVS service is deleted so
that the number of metrics does not grow without bound.
Fixes #734
=> remove IPVS metrics

.github/workflows/ci.yml
Dependabot does not have access to secrets, so skip building containers.
=> .github/ci.yml: Don't build containers for dependabot updates

pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/bgp_policies_test.go
This pull request protects Kube-router from receiving the default route from a misconfigured switch, affecting the node's reachability.
fixes #584 and #586
=> Add a default route 0.0.0.0/8 import policy deny rule

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go
@murali-reddy I had some free time this weekend, so I put together some fixes to the `Cleanup()` functions. Fixes #1021 and #968
I pushed to the `cloudnativelabs` repo, in case you want to rework anything that I put in here, or in case you had a better approach to something. With these fixes, in my cluster, I found that everything was cleaned correctly and there were no more disconcerting errors. I also tried to break down the commits into a pretty granular form.
I changed the one in the NPC controller to utilize the same cleanupStale*() functions that the run control loop uses. This turned out to be pretty easy and pretty clean, so I'm happy with it. It only required a small modification to the cleanupStaleRules() function, other than that, I just pass in empty maps and it does the right …
=> Fix Controller Cleanup() Functions

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/pod.go, pkg/utils/iptables.go
@murali-reddy / @mrueg - This fixes #1136 by ensuring that service rules always come before the firewall rules and that the explicit accept is always at the end of the firewall rules.
@murali-reddy I pushed this to cloudnativelabs so that you could change it as you want. I feel like it makes more sense for the `0x20000` accept rule to be handled in the same way that the firewall rules are (with the npc buffer and `save`/`restore`), but there were some complications that made this more difficult. Mostly because `cleanupStaleRules()` won't work on `KUBE-ROUTER-INPUT`, `KUBE-ROUTER-FORWARD`, and `KUBE-ROUTER-OUTPUT` to get rid of previous occurrences of the rule.
So I had to create some additional functions to handle appending in a way that wouldn't make multiple rules. I feel like using …
=> fix(npc): ordering of firewall / service rules

pkg/controllers/routing/ecmp_vip.go
ensure withdrawn external IP's on service update, are not used by any 
other service. i.e) check if external IP really not used by any service
Fixes #1154
=> ensure withdrawn external IP's on service update, are not used by any other service

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/utils.go, pkg/controllers/routing/network_routes_controller.go
@mrueg @murali-reddy 
I was a little quick on this one. I added a check for `IsFatal()` (which returns false when the path doesn't exist) to some of the error checks for `utils.SetSysctl()`. However, for some of the conditions, this just stops us from logging messages (as the error handling doesn't results in only a logging statement), which isn't helpful.
For the cases of DSR, we probably want the condition to be fatal even if `utils.SetSysctl()` isn't able to find the path (which was the previous behavior).
=> fix(sysctl): revert is fatal check for some conditions

pkg/controllers/proxy/network_services_controller.go
This fixes a bug when the string representation of the fwmark is contained by an existing ip rules. 
for example, if existing ip rules:
32764:	from all fwmark 0x8ef lookup 78
new fwmark to be added: 0x8e
result: the ip rule add command won't be executed.
=> fix bug when adding ip rule for fwmark

pkg/controllers/proxy/network_services_controller.go
Fixes #1196 
Found a couple of bugs in the way that the Network Services Controller handles hairpinning updates.
Specifically:
* Hairpinning wasn't being updated on service / endpoint updates and only on startup / full sync
* The check for existing hairpinning rules was returning true as soon as any of the existing host rules matched any of the perspective add rules. This caused NSC to exit the check early and find matches incorrectly.
=> Fix Hairpinning

pkg/controllers/netpol/network_policy_controller.go, pkg/metrics/metrics_controller.go
@mrueg @murali-reddy 
@MikeSpreitzer pointed out that these metrics are already present in the histogram type as *_count and *_sum and these two added metrics just add duplicates. I've also proved out in my own environments that these metric values are identical to the ones already carried in the histogram.
=> Remove Duplicate Iptables Sync Metrics

docs/user-guide.md, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/proxy/utils.go, pkg/options/options.go
FYI @murali-reddy / @mrueg 
I was sitting down to fix the dangling mangle iptables declarations and consolidate them into KUBE-ROUTER chains, but I found that I kept running afoul of the way external IP services are handled in the NSC. The logic is very complicated and keeps bouncing around with multiple permanent objects being tracked.
This attempts to simplify the external IP service handling into something that is more contained, has specific purposes, is better laid out by functionality, and can hopefully be modified more easily in an upcoming PR.
=> Refactor ExternalIP Service Handling

pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go
This patch explicitly sets `local-address` with node's advertise-ip for each neighbor configuration.
=> start peering connection to neighbors from node's advertise-ip

docs/bgp.md, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/bgp_policies_test.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/utils.go, pkg/controllers/routing/utils_test.go
fixes #586 adding another option for protecting required routes.
=> feat(bgp): add custom BGP import rejection policy support via node annotation

pkg/controllers/netpol/network_policy_controller.go
Missed this in my review of #1261. Without this, it is missing quotes and iptables-restore fails to function.
=> fix(NPC): add missing quotes

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go, pkg/utils/node.go
Fixes kube-router so that it mostly leaves MTU alone. I'm not 100% sure about this PR as these MTU reductions seem to have come out of #102, #108, & #109 all of which are a bit light on details about why reducing MTU saw performance improvements.
What I suspect may be the case is that it's possible that the `ip` command may not have originally reduced the MTU when building `ipip` tunnels. However, it is now doing so, so our reduction of MTU actually results in a very small MTU size when overlay networking is enabled and caused #1033.
Proof that creating an `ipip` device type reduces the MTU of the tunnel link automatically in recent tooling/kernels:
```
...
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
...
...
...
```
Given that, I don't …
=> Fix Multiple Reductions in MTU

pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go
Rather than setting BGP Graceful Restart on both IPv4 and IPv6 regardless of which family is enabled, check the current mode via nrc.isIpv6 and only set on appropriate family.
Note, this mode is exclusive as the current portions of NRC kube-router code are only meant to work with IPv4 or IPv6 not both at the same time.
Fixes #1323
FYI @camrossi
=> fix(bgp): set graceful restart on enabled family

pkg/controllers/proxy/service_endpoints_sync.go
DSR IPVS entries inherently don't have a protocol, so don't check for protocol with these services and ensure that they are cleaned up correctly.
Fixes #1328
=> fix(NSC): don't check protocol on DSR svcs

.gitignore, pkg/utils/ipset.go, pkg/utils/iptables.go
This PR logs `ipset` and `iptables` commands at log level 9.
I've recently encountered an issue with Kubernetes v1.24.0 and
`kube-router` v1.5.1 where the node's network goes bonkers as soon as
`NetworkPolicyController::syncNetworkPolicyChains` is executed (last log
line is "Syncing network policy chains took 48.780838ms"). After that,
`ssh` freezes and `kubelet` becomes inacessible.
Debugging this issue proved to be quite daunting, specially due to the
lack of insight on which network policies are being applied.
Adding these logs have helped the debugging process immensely so far.
=> logging ipset/iptables commands

build/image-assets/iptables-wrapper-installer.sh
Kubernetes iptables wrapper uses `-gt` while kube-router uses `-ge` in the iptables entries number comparison
https://github.com/kubernetes-sigs/iptables-wrappers/blob/70d7897da19aad7749b4f7ae46cb51e3c07c95b9/iptables-wrapper-installer.sh#L124-L128
```
if [ "\${num_legacy_lines}" -gt "\${num_nft_lines}" ]; then
mode=legacy
else
mode=nft
fi
```
This leads to inconsistency in case we have the same number of lines for both modes.
=> fix(iptables) mode selection fixed

docs/user-guide.md
@mrueg @jnummelin
Add warning about userspace netfilter tooling not staying in sync between daemonset and the host's userspace.
While it's dubious how many of our users have actually read the requirements section in the user-guide, it at least makes the information concerning the issues found in #1370 accessible for the people that read the docs.
=> doc(user-guide.md): add info for netfilter tooling

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
@aauren This should remove the warnings in CI and update the used actions to the latest version.
Context: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> .github: Update github actions

.github/workflows/ci.yml, RELEASE.md
@aauren I believe this should allow you to tag release candidates without updating :latest
=> .github: Allow tagging RCs without updating :latest

docs/bgp.md, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/network_routes_controller.go
=> Support for kube-router.io/peer.localips annotation

.github/ISSUE_TEMPLATE/dual_stack_issue_report.md, docs/ipv6.md
@mrueg 
This updates the IPv6 documentation on the default branch to include up-to-date information on the current status of dual-stack support integration.
This goes hand-in-hand with the v2.0.0-rc1 pre-release that was just made.
=> doc(ipv6.md): update for increased dual-stack support

docs/ipv6.md
@mrueg sorry, one more addition for the docs
* Make dual-stack spelling consistent with other places in the doc and upstream
* Add a link to a release candidate from v2.0.0 pre-release
* Clean up wording in enabling dual-stack section
* Add information about policy dependence on enabled IP families
=> Add More Infor to DualStack Docs

pkg/controllers/proxy/network_services_controller.go
@mrueg @XANi
nsc.podCIDR won't exist when `--run-router` is not enabled. In all other references we gate the usage of it behind a check for it existing, somehow this one slipped through. This should fix that and allow people to use `--run-proxy` without `--run-router`.
Fixes #1434
=> fix(NSC): add check for podCidr before use

pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/network_routes_controller.go, pkg/metrics/metrics_controller.go
The bgp sent metric was only counted for pod routed.
VIP routes, advertised via bgp, weren't.
This will also count for VIP routes advertisements and withdraws.
To distinguish between the three types, a new label was added.
=> Extend bgp sent metric

pkg/controllers/routing/network_routes_controller.go
Fixes the "too many colons in address" issue when the primary IP is an IPv6 address.
Tested on an ipv6-only cluster
=> use JoinHostPort for GRPC listen address

docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
When enabled, generate the router id by hashing the primary IP. With this no explicit router id has to be provided on IPv6-only clusters.
Tested on a (small) IPv6-only cluster.
=> add generation of router id based on hash of primary IP

pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/bgp_policies_test.go, pkg/controllers/routing/ecmp_vip.go
@mrueg @rwagoner
This fixes some issues with the unit tests that we've been having on the prep-v2.0 branch as well as fixes #1443 where only the original ClusterIP was advertised even though `PreferDualStack` was added as an IP Family attribute on the service and the kube-controller-manager put multiple IPs on the service.
=> IPv6 Issue Fixes

.github/workflows/ci.yml
@mrueg 
Hopefully this removes all of the warnings that we get about NodeJS 12 not being supported any longer, but at the very least it should bring us current with new versions of actions.
=> feat(ci.yml): update github action versions

pkg/controllers/netpol/policy.go
Previously, IPBlocks (like srcIPBlocks) only contained a single IP Family which meant that a `len() > 0` would indicate that an IP block had been defined in the NetworkPolicy.
However, now the IPBlocks structs are IP family specific which means that they will always contain 2 entries, one for the IPv4 family and one of the IPv6 family. Which means that this condition will evaluate to true for all NetworkPolicies and waste system resources creating empty ipsets and bad iptables rules.
=> Fix IP Block processing

docs/dsr.md, docs/tunnels.md, docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go, pkg/controllers/routing/utils.go, pkg/options/options.go
Cloud environments like Azure do not support IP-IP tunnel between VMs. This changeset adds an option in Kube-router to use UDP encapsulation on top of IP-IP tunnel (Foo Over UDP (FoU)).
=> Support for FoU encapsulation for IPIP tunnel

.github/workflows/ci.yml
@mrueg 
In setup-go@v4 it changed to enabling caching by default which looks for a go modules file to check the cache. This means that the checkout needs to be processed before the setup-go action.
=> fix(ci): checkout before go setup

.github/workflows/ci.yml, Makefile
@mrueg 
Add caching to the kube-router build, test, moq, & lint Makefile targets
With a primed cache I've found that this greatly increases the responsiveness of each of this make targets:
```
Standard: make kube-router  0.06s user 0.03s system 0% cpu 28.231 total
With Primed Cache: make kube-router  0.05s user 0.04s system 3% cpu 2.340 total
Standard: make test  0.18s user 0.07s system 0% cpu 36.072 total
With Primed Cache: make test  0.20s user 0.04s system 21% cpu 1.171 total
Standard: make lint  0.18s user 0.08s system 0% cpu 40.760 total
With Primed Cache: make lint  0.20s user 0.04s system 1% cpu 14.314 total
```
I _think_ that we might be able to gain some performance out of the `container` target as well by adding caching to the Dockerfile similar to: …
=> CI Add Caching

pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/ecmp_vip_test.go
FYI @mrueg 
Annotations were taken into account during startup, but after they were advertised the affect of annotations was only additive because we were only tracking current state of VIPs that should be advertised and not taking into account VIPs that should be withdrawn for anything other than service locality.
Fixes #1491
=> fix(NRC): withdraw advertised VIPs based on annotation

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kubeadm-kuberouter-all-features-dsr.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml, docs/load-balancer-allocator.md, docs/user-guide.md, pkg/cmd/kube-router.go, pkg/controllers/lballoc/lballoc.go, pkg/controllers/lballoc/lballoc_test.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/healthcheck/health_controller.go, pkg/options/options.go
This adds a simple controller that will watch for services of type LoadBalancer and try to allocated addresses from the specified IPv4 and/or IPv6 ranges. It's assumed that kube-router (or another network controller) will announce the addresses.
As the controller uses leases for leader election and updates the service status new RBAC permissions are required.
Tested on a small IPv6-only cluster, so IPv4/dual stack is not tested outside the unit tests.
Fixes https://github.com/cloudnativelabs/kube-router/issues/242
=> add loadbalancer address allocator

pkg/controllers/routing/bgp_policies.go
Previously when a user selected to override the next-hop via `GoBGP's NextHopActions: Self` functionality, we did it for all exported routes. However, in a dual-stack use-case this causes problems for internal pod IP routes that are spread via BGP advertisements.
Currently, kube-router only peers with an internal peer once over whatever it's primary IP is according to it's Kubernetes node information. This means that when overriding next-hop the IP is either an IPv4 or IPv6 address depending on how the node has configured itself. Therefore when it attempts to add a route for an IPv6 address and override next-hop is configured, if the node's primary IP was an IPv4 address this will not succeed as a next-hop for an IPv6 address cannot be an IPv4 gateway.
Rather than making the code base …
=> feat(bgp_policies.go): don't override-nexthop for internal peers

pkg/controllers/routing/network_routes_controller.go
Add a sanity check before attempting to insert a route. Prevents issue as seen by user: https://kubernetes.slack.com/archives/C8DCQGTSB/p1691000323278989
kube-router should have the right checks on the advertisement side to not ever do this, but its possible that we receive routes from other announcers besides kube-router.
=> Add Check for IP Family

.goreleaser.yml, Makefile
Add goreleaser and Makefile entries to build/deploy riscv64 assets
=> Add RISC-V 64 support

.github/workflows/ci.yml
@mrueg - it looks like ppc64le support was old enough to be built by Jenkins, so maybe it was intentionally left out of GitHub actions when you made that migration?
riscv64, was just added by #1525 but after merging I noticed that it didn't look to be building an image for that architecture: https://github.com/cloudnativelabs/kube-router/actions/runs/6004672360/job/16285750933
These are both architectures that are added to the Makefile, but that we don't currently build for. riscv64 was added in:
https://github.com/cloudnativelabs/kube-router/pull/1525 and ppc64le was added in: https://github.com/cloudnativelabs/kube-router/pull/847
=> feat(ci.yml): add ppc64le and riscv64 to ci

.github/workflows/ci.yml, Makefile
@iggy @aauren Since the alpine image we use does not have a riscv64 architecture, we can't build riscv64 images. We can still build a riscv64 binary with goreleaser though.
We'd need to wait for https://gitlab.alpinelinux.org/alpine/aports/-/issues/13269
=> Partially revert riscv64 support

.github/workflows/close_stale.yml
@mrueg 
This has been something that this repo has needed for a while now, and thanks to GitHub actions, this appears pretty easy to do now.
This will make it so that issues will get warned after 30 days of inactivity and closed 5 days after that if no comments have been made. PRs will be warned after 60 days of inactivity and closed after 10 days if no comments or updates have been made.
Maintainers can stop this workflow for specific issues and PRs by adding the `override-stale` label to the issue or PR. Additionally, PRs opened by dependabot and tagged with `dependencies` will not be marked or reaped.
Documentation taken from:
* https://github.com/actions/stale
* https://github.com/actions/stale/blob/main/action.yml
* https://docs.github.com/en/actions/using-workflows/workflow-syntax-fo …
=> feat(close_stale.yml): add workflow for closing stale issues & PRs

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/policy.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go, pkg/metrics/metrics_controller.go
@brandond @ChristianCiach
This work was taken from @brandond's fork of kube-router for k3s: https://github.com/brandond/kube-router/tree/metrics-var
The primary work done there was to:
* Improve the performance of the network policy controller (NPC) by reducing the number of shell calls made to ipset when syncing policies to help improve the performance problems reported by @ChristianCiach here: https://github.com/k3s-io/k3s/discussions/8321
* Improve observability in the NPC by adding metrics for number of iptables chain and number of ipsets that kube-router manages
* Improve observability in the NPC by adding metrics for save / restore of iptables / ipsets per family
* Added ability to swap out metrics handlers for projects that consume kube-router as a library
All the work here was …
=> Add k3s Improvements

cmd/kube-router/kube-router_test.go, docs/generic.md, docs/introduction.md, docs/kubeadm.md, docs/user-guide.md, go.mod, go.sum, pkg/cmd/kube-router.go, pkg/controllers/proxy/network_services_controller.go, pkg/version/version.go
@mrueg 
Fixes a critical bug for v2.0.0 of kube-router mentioned in #1558 
Also addresses some concerns about lack of information in the logs about the backward compatibility break in v2.0.0 by implementing a user requested logging feature: https://github.com/cloudnativelabs/kube-router/issues/1555#issuecomment-1757631609
Finally, this also fixes up some old / broken documentation and fixes #1546
=> Bug Fixes for v2.0.0

pkg/controllers/routing/network_routes_controller.go
Hello folks,
I was having issues with binding overlay ipip tunnels to specific device. I would like to see option to disable this behavior.
My usecase is that I have many nodes on one L2 network but few (1 at this time) i have "off-site", connected with a wireguard VPN. When kube-router builds ipip tunnel it is confused and binds tunnel to interface BELOW the VPN so instead of running ip-ip through VPN it tries to run it through default VPN but with VPN local/remote addresses. Which fails obviously.
OTOH I'm not really sure why the binding is there - is there any reason for it? Maybe better solution would be to just remove it?
Thanks for your opinion
=> feat: Option to disable overlay tunnel device binding

docs/user-guide.md, pkg/cmd/kube-router.go, pkg/metrics/metrics_controller.go, pkg/options/options.go, pkg/utils/utils.go
In the situation that you have multiple interfaces/IP addresses, we want to be able to specify which one we want to expose the prometheus metrics on.
This is the follow up to #1244 with the PR feedback addressed.
=> prometheus metrics: add option to specify listen address

pkg/controllers/proxy/hairpin_controller.go, pkg/controllers/proxy/linux_networking.go, pkg/controllers/proxy/linux_networking_moq.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/utils.go, pkg/healthcheck/health_controller.go
It used to be that the kubelet handled setting hairpin mode for us: https://github.com/kubernetes/kubernetes/pull/13628
Then this functionality moved to the dockershim:
https://github.com/kubernetes/kubernetes/pull/62212
Then the functionality was removed entirely:
https://github.com/kubernetes/kubernetes/commit/83265c9171f
Unfortunately, it was lost that we ever depended on this in order for our hairpin implementation to work, if we ever knew it at all. Additionally, I suspect that containerd and cri-o implementations never worked correctly with hairpinning.
Without this, the NAT rules that we implement for hairpinning don't work correctly. Because hairpin_mode isn't implemented on the virtual interface of the container on the host, the packet bubbles up to the kube-bridge. At some point …
=> fix(hairpin): set hairpin_mode for veth iface

pkg/controllers/proxy/network_services_controller.go
@mrueg 
In some cases it is possible for Endpoint.Conditions.Ready to be nil during the early stages of initialization. When this happens it causes kube-router to segfault. This fix tests for nil before testing for Ready.
Error looks like:
```log
2023-12-08T19:26:16.577929290Z E1208 19:26:16.577532       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)                                                                    
2023-12-08T19:26:16.577944838Z goroutine 257 [running]: …
```
=> fix(NSC): handle endpoint slice ready nil

daemonset/generic-kuberouter-all-features-advertise-routes.yaml, daemonset/generic-kuberouter-all-features.yaml, daemonset/generic-kuberouter-only-advertise-routes.yaml, daemonset/generic-kuberouter.yaml, daemonset/kube-router-all-service-daemonset-advertise-routes.yaml, daemonset/kube-router-all-service-daemonset.yaml, daemonset/kube-router-firewall-daemonset.yaml, daemonset/kube-router-proxy-daemonset.yaml, daemonset/kubeadm-kuberouter-all-features-hostport.yaml, daemonset/kubeadm-kuberouter-all-features.yaml, daemonset/kubeadm-kuberouter.yaml, pkg/controllers/proxy/linux_networking.go
Since #1582  was merged, we now rely upon having access to the host's PID namespace in order to detect which veth device a given container doing hairpinning is using. As such, we now add it to the daemonsets in the example and attempt to direct users upon certain errors.
=> Fix Ddd hostPID to Daemonsets

docs/user-guide.md, pkg/controllers/proxy/linux_networking.go, pkg/controllers/proxy/network_services_controller.go, pkg/options/options.go
This is a feature that has been requested a few times over the years and would bring us closer to feature parity with other k8s network implementations for service proxy.
Adds the options:
```
--service-tcp-timeout duration                  Specify TCP timeout for IPVS services in standard duration syntax (e.g. '5s', '1m'), default 0s preserves default system value (default: 0s)
--service-tcpfin-timeout duration               Specify TCP FIN timeout for IPVS services in standard duration syntax (e.g. '5s', '1m'), default 0s preserves default system value (default: 0s)
--service-udp-timeout duration                  Specify UDP timeout for IPVS services in standard duration syntax (e.g. '5s', '1m'), default 0s preserves default system value (default: 0s)
```
Keeps backwards compatibility …
=> feat(NSC): add IPVS service timeouts

.golangci.yml, docs/user-guide.md, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/bgp_policies_test.go, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/ecmp_vip_test.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go
Adds support for `spec.internalTrafficPolicy` (introduced in k8s v1.26) and fixes `spec.externalTrafficPolicy` to behave according to upstream indicated behavior: https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-policies
At this point, we still don't handle terminating endpoints as specified in the documentation. However, I think that this is a good bit of work, so its probably best to handle that in a future PR.
Relates to #1597 - However, #1597 won't be completely finished until we implement the specialized draining procedure and pass all traffic policy related e2e tests.
=> Feature: Support All Upstream Traffic Policies

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/nodeport_healthcheck.go, pkg/controllers/proxy/service_endpoints_sync.go
The big change here is that kube-router now implements the NodePort HealthCheck feature that is best described here: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-loadbalancer
Blurb from the commit for this feature is:
>NodePort Health Check has long been part of the Kubernetes API, but
kube-router hasn't implemented it in the past. This is meant to be a
port that is assigned by the kube-controller-manager for LoadBalancer
services that have a traffic policy of `externalTrafficPolicy=Local`.
>When set, the k8s networking implementation is meant to open a port and
provide HTTP responses that inform parties external to the Kubernetes
cluster about whether or not a local endpoint exists on the node. It
should return a 200 status if the node …
=> Make kube router healthchecknodeport aware

.github/dependabot.yml
@aauren this will reduce the number of PRs that dependabot makes for the Kubernetes deps.
=> dependabot: Group kubernetes dependencies

daemonset/kubeadm-kuberouter-all-features-dsr.yaml, docs/dsr.md
Add documentation to improve user DSR experience about mounting `/etc/iproute2/rt_tables` into the container when kube-router runs as a daemonset.
Based upon feedback from #1616 from @s11fsch
=> doc(DSR): add /etc/iproute2/rt_tables caveat

docs/dsr.md, pkg/controllers/proxy/linux_networking.go, pkg/controllers/routing/pbr.go, pkg/utils/linux_routing.go
@mrueg 
Ever since version v6.5.0 of iproute2, iproute2 no longer automatically creates the /etc/iproute2 files, instead preferring to add files to /usr/lib/iproute2 and then later on /usr/share/iproute2.
This adds fallback path matching to kube-router so that it can find /etc/iproute2/rt_tables wherever it is defined instead of just failing.
This also means people running kube-router in containers will need to change their mounts depending on where this file is located on their host OS. However, ensuring that this file is copied to `/etc/iproute2` is a legitimate way to ensure that this is consistent across a fleet of multiple OS versions.
=> fix(rt_tables): add path fallback logic

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go
Only attempt to setup DSR inside containers for local endpoints. Setting up DSR inside the containers network namespace requires local pods / endpoints.
Fixes #1640 
@opipenbe - I tested this locally with my smaller development cluster and it appeared to work correctly, however, I would be very appreciative if you would test this in your cluster as well. A container should be built as part of the GitHub Actions CI on this PR, you can look in the CI log for a link to [kube-router-git](https://hub.docker.com/r/cloudnativelabs/kube-router-git/tags) for the newly built kube-router.
One thing that I still don't quite have an answer for though, is why this didn't also have this same error for you under kube-router v1.6.0 as the code path was essentially the same: …
=> fix(DSR): setup DSR inside pod on local eps only

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/policy.go, pkg/controllers/netpol/policy_test.go, pkg/controllers/netpol/utils.go, pkg/utils/ipset.go
ipset name has prefix "inet6:" for ipv6. so ip6tables rule also need to convert ipset name.
Issue: #1653
=> fix: wrong ipset name used by ip6tables.

docs/user-guide.md, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/controllers/proxy/hairpin_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go, pkg/utils/node.go, pkg/utils/node_test.go
kube-router v2.X introduced the idea of iptables and ipset handlers that allow kube-router to be dual-stack capable. However, the cleanup logic for the various controllers was not properly ported when this happened. When the cleanup functions run, they often have not had their controllers fully initialized as cleanup should not be dependant on kube-router being able to reach a kube-apiserver.
As such, they were missing these handlers. And as such they either silently ended up doing noops or worse, they would run into nil pointer failures.
This corrects that, so that kube-router no longer fails this way and cleans up as it had in v1.X.
@vladimirtiukhtin - I tested this in my environment and found it worked correctly, but if you wouldn't mind checking as well, that would be helpful to …
=> Fix Cleanup Code for v2.x

pkg/controllers/proxy/linux_networking.go, pkg/controllers/proxy/network_service_graceful.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/proxy/utils.go
Don't attempt to setup DSR for pods where `hostNetwork: true` is set.
DSR doesn't work for hostNetwork'd pods and will only end up causing bizarre problems when kube-router attempts to make it happen anyway. Now, we emit an error early and don't attempt to let it go any further before breaking.
=> Fix DSR Boundary Conditions

daemonset/kubeadm-kuberouter-all-features-dsr.yaml, pkg/controllers/proxy/hairpin_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/healthcheck/health_controller.go
After taking another look at it, I realized that the hairpin controller that I had originally created to ensure that hairpin mode was enabled on the pod's network namespace link was entirely superfluous. Instead, user's should be using the little known `hairpinMode` of the bridge CNI plugin for kube-router.
This plugin is already in the pod's network namespace when it needs to run and is much more reliable than the controller that I created.
For now I'm leaving the code, but just removing references to it so that I can bring it back in the future if I decide that its helpful. However, it had quite a few problems with it, as mentioned in #1630.
I've also updated the dsr reference daemonset to include this mode, as I'm not sure why this was left out in the first place. The docs in the …
=> Remove Hairpin Controller

pkg/controllers/netpol/network_policy_controller.go, pkg/utils/ipset.go, pkg/utils/ipset_test.go
@mrueg / @manuelbuil
Attempts to separate IP families within the different ipset handlers. This has likely been an issue since the first dual-stack implementation was contributed, but hasn't been discovered until now. The problem was that ipset was being utilized the same way that iptables was where different handlers implicitly meant different families. However, the ipset command doesn't differentiate that way, it has one command that always contains both sets. This was likely missed during the port to dual stack that was contributed ~2 years ago.
Fixes #1665
=> Fix ipset Duplication Across Handlers

pkg/controllers/proxy/network_services_controller.go
This allows VIPs to be shared between services.
Fixes #1671
=> fix(nsc): TCPMSS rules are created per tcp service

.github/workflows/ci.yml, Dockerfile, Makefile
@mrueg 
Revert because of issue with iptables v1.8.10 no longer working with -C check.
Still testing this in a local cluster to make sure that the problem doesn't re-occur. Long term, this needs to be chased down with upstream netfilter, but for now this should at least help us get to a stable version of kube-router on the v2.x release line.
Fixes: #1676
=> feat(alpine): revert 3.19 -> 3.18

pkg/controllers/proxy/utils.go
Fix an instance of static subnet referencing which causes issues with IPv6 use-cases for hairpin rules.
=> fix(utils.go): static /32 subnet mask reference

pkg/controllers/proxy/linux_networking.go
Remove extra routes added by iproute2 when addresses are added to interfaces which block IPv6 service VIPs from routing from the host.
See: https://github.com/cloudnativelabs/kube-router/issues/1698
Fixes: https://github.com/cloudnativelabs/kube-router/issues/1698
=> fix(linux_networking.go): remove dangling IPv6 routes

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/utils.go, pkg/controllers/proxy/utils_test.go
Currently, kube-router just lists all IPVS services on the host and then adds the load balancing service IPs to kube-router-svip blindly. However, this assumes that the only IPVS entries are entries that kube-router has originated and that the user isn't using IPVS.
We want to make sure that we are only creating rules for services that we are authoritative for. So to this end, we now double-check that this is one of our services before adding rules that may effect it.
Fixes: #1685
=> fix(NSC): ensure kube-router owns kube-router-svip

pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/proxy/network_services_controller.go, pkg/utils/iptables.go, pkg/utils/iptables_test.go
@mrueg @k6av
This fixes the problem where if network policy is applied before any communication between two pods, all subsequent communication fails because the two pods aren't able to discovery each other.
Fixes: #1701
=> fix: allow basic ICMPv6 neighbor discovery

pkg/utils/iptables.go, pkg/utils/iptables_test.go
This fixes kube-router trying to use `icmp` instead of `icmpv6` when creating common ICMP rules with ip6tables.
Fixes: #1712
=> fix: select ICMP version for common ICMP rules

daemonset/kubeadm-kuberouter-all-features-dsr.yaml, docs/dsr.md
Change the mount examples to use whole directory as the socket file might change during runtime and thus mounting the single file might break the behaviour in case of container runtime restarts.
Also simplified all the examples to use containerd as CRI as it's probably the most used CRI.
Fixes #1719
=> Enhance DSR docs aroung CRI socket mounting

go.mod, go.sum, pkg/cmd/kube-router.go, pkg/controllers/netpol/network_policy_controller.go, pkg/controllers/netpol/network_policy_controller_test.go, pkg/controllers/netpol/pod.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/network_services_controller_test.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/proxy/utils.go, pkg/controllers/proxy/utils_test.go, pkg/controllers/routing/bgp_peers.go, pkg/controllers/routing/bgp_policies.go, pkg/controllers/routing/bgp_policies_test.go, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/ecmp_vip_test.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go, pkg/controllers/routing/pbr.go, pkg/controllers/routing/utils.go, pkg/utils/linux_routing.go, pkg/utils/linux_routingtest.go, pkg/utils/node.go, pkg/utils/node_test.go
@jnummelin @rbrtbnfgl @mrueg 
This prepares the way for broader refactors in the way that we handle nodes by:
* Separating frequently used node logic from the controller creation steps
* Keeping reused code DRY-er
* Adding interface abstractions for key groups of node data and starting to rely on those more rather than concrete types
* Separating node data from the rest of the controller data structure so  that it smaller definitions of data can be passed around to functions  that need it rather than always passing the entire controller which  contains more data / surface area than most functions need.
Eventually the changes here should better support the work that will need to happen to fix #1738 #676
=> Refactor: Abstract Node Info

pkg/controllers/routing/bgp_policies_test.go, pkg/controllers/routing/network_routes_controller_test.go
Some small nits I stumbled upon while spelunking through the test cases.
=> Remove some unused error fields from test cases

pkg/bgp/id.go, pkg/bgp/id_test.go, pkg/bgp/parse.go, pkg/controllers/routing/network_routes_controller.go, pkg/controllers/routing/network_routes_controller_test.go, pkg/controllers/routing/utils.go, pkg/controllers/routing/utils_test.go, pkg/routes/linux_routes.go, pkg/routes/pbr.go, pkg/routes/route_sync.go, pkg/routes/route_sync_test.go, pkg/tunnels/linux_tunnels.go, pkg/tunnels/linux_tunnels_test.go
@mrueg @jnummelin @twz123 @rbrtbnfgl
Another refactor PR that is attempting to pull functionality out of NetworkRoutesController in prep for some work that I want to do with `injectRoute()`.
This time instead of tossing the functionality into the `utils` package like I did with `node.go`, I'm attempting to be a bit more Go idiomatic and naming the packages appropriately. This also helps the function names to be a bit shorter as context can be derived from the package name.
Note that with the `routes` package I'm just barely scratching the surface of what I want to do there long term. Trying to keep these refactors at least a bit controlled so that they don't get too big. Ideally there would probably be a lot more functionality that would get put into that package. And also #1697 would …
=> More injectRoute() Preparation Refactors

Makefile, build/test-scripts/unit_test_timing.py, pkg/bgp/id.go, pkg/controllers/lballoc/lballoc.go, pkg/controllers/lballoc/lballoc_test.go, pkg/controllers/proxy/linux_networking_moq.go, pkg/controllers/routing/ecmp_vip_test.go, pkg/utils/node.go
@mrueg @twz123 @rbrtbnfgl
Fixes a couple of things:
* During one of the recent refactors, we lost the fact that the router-id for BGP should default to the IPv4 address when it isn't otherwise specified
* Fixes a potential for the IP addresses on nodes to not obey the ordering of internal first then external. This mostly impacted tests, but would have eventually impacted users as well once a release was createdc
* Removes a potential race condition from LoadBalancerAllocator tests
* Reduces the total unit test run times by setting `t.Parrallel()` on ecmp_vip_test.go which was the longest test in the suite
* It would be nice to set this on more tests in the `routing` suite, but unfortunately, we can't use it any time we actually start a gobgp server because it has several global vars that …
=> Fix various issues with refactors

pkg/cri/remote_runtime.go
@mrueg 
When we used DialContext() before it was deprecated, it manually set the default resolver to passthrough. NewClient() appears to not do this, and then several versions of grpc ago, they defaulted to the DNS resolver which broke our DSR implementation with CRI compatible container engines.
I'm not 100% sure that there isn't a better way to specify this, but I spent 20 - 30 minutes poking around the gRPC code base and I don't think that I can see an easy way to do this outside of specifying it this way.
Furthermore, the project itself seems to advocate for this approach in comments like those on: https://github.com/grpc/grpc-go/issues/1846
Fixes: #1754
=> fix(dsr): change grpc resolver to passthrough

pkg/healthcheck/health_controller.go, pkg/metrics/metrics_controller.go
https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/net/http/pprof/pprof.go;l=100
metrics may just metrics
if enable pprof in metrics server, the flags `--enable-pprof` may be confused.
=> fix: avoid to use http.DefaultServeMux which includes defaults routes inited by go like /debug/pprof

pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/ecmp_vip.go, pkg/controllers/routing/ecmp_vip_test.go
@mrueg @twz123 @rbrtbnfgl
Over time, feedback from users has been that our interpretation of how the kube-router service.local annotation interacts with the internal traffic policy has been that it is too restrictive.
It seems like tuning it to fall in line with the local internal traffic policy is too restrictive. This commit changes that posture, by equating the service.local annotation with External Traffic Policy Local and Internal Traffic Policy Cluster.
This means that when service.local is set the following will be true:
* ExternalIPs / LoadBalancer IPs will only be available on a node that hosts the workload
* ExternalIPs / LoadBalancer IPs will only be BGP advertised (when enabled) by nodes that host the workload
* Services will have the same posture as External Traffic Policy …
=> feat(NSC): change service.local internal traffic policy posture

pkg/controllers/routing/network_routes_controller.go
@zerkms @mrueg @twz123 @rbrtbnfgl
Back in commit 9fd46cc when I was pulling out the krnode struct I made a mistake in the `syncNodeIPSets()` function and didn't grab the IPs of all nodes, instead I only grabbed the IP of the current node multiple times.
This caused other nodes (besides the current one) to get removed from the `kube-router-node-ips` ipset which ensures that we don't NAT traffic from pods to nodes (daemons and HostNetwork'd items).
This should fix that problem.
Fixes #1778
=> fix(NRC): find all node IPs for NAT exclusion

pkg/controllers/proxy/network_services_controller.go, pkg/utils/sysctl.go
Setting rp_filter to 2 when it is 0 will override its status to be always enabled (in the loose mode).
This behavior could break some networking solutions as it made packet admission rules more strict.
Reference: https://github.com/cloudnativelabs/kube-router/pull/1651#issuecomment-2561151350 and subsequent
=> fix(NSC): only set rp_filter to 2 if it is 1

pkg/controllers/netpol/policy.go
This PR should fixes #1732 to refresh the rules before syncing the policy.
=> Added `ipset.Save()` at the start of `syncNetworkPolicyChains`

docs/user-guide.md, pkg/controllers/routing/network_routes_controller.go, pkg/options/options.go
Introduces the option `--gobgp-admin-port` which allows for setting the port that will be used for exposing GoBGP's grpc port.
Fixes: #1816
=> feat(options): add flag for GoBGP grpc port

pkg/cmd/kube-router.go
If --master is specified, but --kubeconfig is not, use in-cluster config and override the API server host.
This would fix #1614.
=> Support --master without --kubeconfig

pkg/controllers/proxy/linux_networking.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/proxy/service_endpoints_sync.go, pkg/controllers/proxy/utils.go, pkg/controllers/routing/bgp_policies.go, pkg/routes/pbr.go, pkg/tunnels/linux_tunnels.go, pkg/utils/ip.go, pkg/utils/ip_test.go, pkg/utils/linux_routing.go, pkg/utils/utils.go
Not making direct exec calls to user binary interfaces has long been a principle of kube-router. When kube-router was first coded, the netlink library was missing significant features that forced us to exec out. However, now netlink seems to have most of the functionality that we need.
This converts all of the places where we can use netlink to use the netlink functionality.
The current state of this PR is untested and still needs to undergo significant testing:
=> feat: convert execs to ip to netlink calls

pkg/controllers/netpol/network_policy_controller_test.go, pkg/controllers/netpol/policy.go, pkg/controllers/proxy/network_services_controller.go, pkg/controllers/routing/network_routes_controller.go, pkg/utils/ipset.go, pkg/utils/ipset_test.go, pkg/utils/utils.go
Attempt to filter out sets that we are not authoritative for to avoid race conditions with other operators (like Istio) that might be attempting to modify ipsets at the same time.
This still needs some refinement and probably a refactor or two, but wanted to get it out early so that you could test it and see if it actually resolves what you were seeing in #1918. I tried it in my cluster, and after proving that I could see kube-router modifying other ipsets, then applied this change, and saw that it no longer contained references in its output.
FYI @mjnagel @ilrudie
Attempts to fix #1918
=> fix(ipset): ignore non-kube-router ipsets
